//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3053
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

#pragma warning disable 1591

namespace LOGISTICMANAGAMENTSYSTEM.REPORTS.INVOICE {
    
    
    /// <summary>
    ///Represents a strongly typed in-memory cache of data.
    ///</summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "2.0.0.0")]
    [global::System.Serializable()]
    [global::System.ComponentModel.DesignerCategoryAttribute("code")]
    [global::System.ComponentModel.ToolboxItem(true)]
    [global::System.Xml.Serialization.XmlSchemaProviderAttribute("GetTypedDataSetSchema")]
    [global::System.Xml.Serialization.XmlRootAttribute("dsRESICARGO")]
    [global::System.ComponentModel.Design.HelpKeywordAttribute("vs.data.DataSet")]
    public partial class dsRESICARGO : global::System.Data.DataSet {
        
        private V_RESICARGODataTable tableV_RESICARGO;
        
        private global::System.Data.SchemaSerializationMode _schemaSerializationMode = global::System.Data.SchemaSerializationMode.IncludeSchema;
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public dsRESICARGO() {
            this.BeginInit();
            this.InitClass();
            global::System.ComponentModel.CollectionChangeEventHandler schemaChangedHandler = new global::System.ComponentModel.CollectionChangeEventHandler(this.SchemaChanged);
            base.Tables.CollectionChanged += schemaChangedHandler;
            base.Relations.CollectionChanged += schemaChangedHandler;
            this.EndInit();
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        protected dsRESICARGO(global::System.Runtime.Serialization.SerializationInfo info, global::System.Runtime.Serialization.StreamingContext context) : 
                base(info, context, false) {
            if ((this.IsBinarySerialized(info, context) == true)) {
                this.InitVars(false);
                global::System.ComponentModel.CollectionChangeEventHandler schemaChangedHandler1 = new global::System.ComponentModel.CollectionChangeEventHandler(this.SchemaChanged);
                this.Tables.CollectionChanged += schemaChangedHandler1;
                this.Relations.CollectionChanged += schemaChangedHandler1;
                return;
            }
            string strSchema = ((string)(info.GetValue("XmlSchema", typeof(string))));
            if ((this.DetermineSchemaSerializationMode(info, context) == global::System.Data.SchemaSerializationMode.IncludeSchema)) {
                global::System.Data.DataSet ds = new global::System.Data.DataSet();
                ds.ReadXmlSchema(new global::System.Xml.XmlTextReader(new global::System.IO.StringReader(strSchema)));
                if ((ds.Tables["V_RESICARGO"] != null)) {
                    base.Tables.Add(new V_RESICARGODataTable(ds.Tables["V_RESICARGO"]));
                }
                this.DataSetName = ds.DataSetName;
                this.Prefix = ds.Prefix;
                this.Namespace = ds.Namespace;
                this.Locale = ds.Locale;
                this.CaseSensitive = ds.CaseSensitive;
                this.EnforceConstraints = ds.EnforceConstraints;
                this.Merge(ds, false, global::System.Data.MissingSchemaAction.Add);
                this.InitVars();
            }
            else {
                this.ReadXmlSchema(new global::System.Xml.XmlTextReader(new global::System.IO.StringReader(strSchema)));
            }
            this.GetSerializationData(info, context);
            global::System.ComponentModel.CollectionChangeEventHandler schemaChangedHandler = new global::System.ComponentModel.CollectionChangeEventHandler(this.SchemaChanged);
            base.Tables.CollectionChanged += schemaChangedHandler;
            this.Relations.CollectionChanged += schemaChangedHandler;
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.ComponentModel.Browsable(false)]
        [global::System.ComponentModel.DesignerSerializationVisibility(global::System.ComponentModel.DesignerSerializationVisibility.Content)]
        public V_RESICARGODataTable V_RESICARGO {
            get {
                return this.tableV_RESICARGO;
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.ComponentModel.BrowsableAttribute(true)]
        [global::System.ComponentModel.DesignerSerializationVisibilityAttribute(global::System.ComponentModel.DesignerSerializationVisibility.Visible)]
        public override global::System.Data.SchemaSerializationMode SchemaSerializationMode {
            get {
                return this._schemaSerializationMode;
            }
            set {
                this._schemaSerializationMode = value;
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.ComponentModel.DesignerSerializationVisibilityAttribute(global::System.ComponentModel.DesignerSerializationVisibility.Hidden)]
        public new global::System.Data.DataTableCollection Tables {
            get {
                return base.Tables;
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.ComponentModel.DesignerSerializationVisibilityAttribute(global::System.ComponentModel.DesignerSerializationVisibility.Hidden)]
        public new global::System.Data.DataRelationCollection Relations {
            get {
                return base.Relations;
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        protected override void InitializeDerivedDataSet() {
            this.BeginInit();
            this.InitClass();
            this.EndInit();
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public override global::System.Data.DataSet Clone() {
            dsRESICARGO cln = ((dsRESICARGO)(base.Clone()));
            cln.InitVars();
            cln.SchemaSerializationMode = this.SchemaSerializationMode;
            return cln;
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        protected override bool ShouldSerializeTables() {
            return false;
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        protected override bool ShouldSerializeRelations() {
            return false;
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        protected override void ReadXmlSerializable(global::System.Xml.XmlReader reader) {
            if ((this.DetermineSchemaSerializationMode(reader) == global::System.Data.SchemaSerializationMode.IncludeSchema)) {
                this.Reset();
                global::System.Data.DataSet ds = new global::System.Data.DataSet();
                ds.ReadXml(reader);
                if ((ds.Tables["V_RESICARGO"] != null)) {
                    base.Tables.Add(new V_RESICARGODataTable(ds.Tables["V_RESICARGO"]));
                }
                this.DataSetName = ds.DataSetName;
                this.Prefix = ds.Prefix;
                this.Namespace = ds.Namespace;
                this.Locale = ds.Locale;
                this.CaseSensitive = ds.CaseSensitive;
                this.EnforceConstraints = ds.EnforceConstraints;
                this.Merge(ds, false, global::System.Data.MissingSchemaAction.Add);
                this.InitVars();
            }
            else {
                this.ReadXml(reader);
                this.InitVars();
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        protected override global::System.Xml.Schema.XmlSchema GetSchemaSerializable() {
            global::System.IO.MemoryStream stream = new global::System.IO.MemoryStream();
            this.WriteXmlSchema(new global::System.Xml.XmlTextWriter(stream, null));
            stream.Position = 0;
            return global::System.Xml.Schema.XmlSchema.Read(new global::System.Xml.XmlTextReader(stream), null);
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        internal void InitVars() {
            this.InitVars(true);
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        internal void InitVars(bool initTable) {
            this.tableV_RESICARGO = ((V_RESICARGODataTable)(base.Tables["V_RESICARGO"]));
            if ((initTable == true)) {
                if ((this.tableV_RESICARGO != null)) {
                    this.tableV_RESICARGO.InitVars();
                }
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private void InitClass() {
            this.DataSetName = "dsRESICARGO";
            this.Prefix = "";
            this.Namespace = "http://tempuri.org/dsRESICARGO.xsd";
            this.EnforceConstraints = true;
            this.SchemaSerializationMode = global::System.Data.SchemaSerializationMode.IncludeSchema;
            this.tableV_RESICARGO = new V_RESICARGODataTable();
            base.Tables.Add(this.tableV_RESICARGO);
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private bool ShouldSerializeV_RESICARGO() {
            return false;
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private void SchemaChanged(object sender, global::System.ComponentModel.CollectionChangeEventArgs e) {
            if ((e.Action == global::System.ComponentModel.CollectionChangeAction.Remove)) {
                this.InitVars();
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public static global::System.Xml.Schema.XmlSchemaComplexType GetTypedDataSetSchema(global::System.Xml.Schema.XmlSchemaSet xs) {
            dsRESICARGO ds = new dsRESICARGO();
            global::System.Xml.Schema.XmlSchemaComplexType type = new global::System.Xml.Schema.XmlSchemaComplexType();
            global::System.Xml.Schema.XmlSchemaSequence sequence = new global::System.Xml.Schema.XmlSchemaSequence();
            global::System.Xml.Schema.XmlSchemaAny any = new global::System.Xml.Schema.XmlSchemaAny();
            any.Namespace = ds.Namespace;
            sequence.Items.Add(any);
            type.Particle = sequence;
            global::System.Xml.Schema.XmlSchema dsSchema = ds.GetSchemaSerializable();
            if (xs.Contains(dsSchema.TargetNamespace)) {
                global::System.IO.MemoryStream s1 = new global::System.IO.MemoryStream();
                global::System.IO.MemoryStream s2 = new global::System.IO.MemoryStream();
                try {
                    global::System.Xml.Schema.XmlSchema schema = null;
                    dsSchema.Write(s1);
                    for (global::System.Collections.IEnumerator schemas = xs.Schemas(dsSchema.TargetNamespace).GetEnumerator(); schemas.MoveNext(); ) {
                        schema = ((global::System.Xml.Schema.XmlSchema)(schemas.Current));
                        s2.SetLength(0);
                        schema.Write(s2);
                        if ((s1.Length == s2.Length)) {
                            s1.Position = 0;
                            s2.Position = 0;
                            for (; ((s1.Position != s1.Length) 
                                        && (s1.ReadByte() == s2.ReadByte())); ) {
                                ;
                            }
                            if ((s1.Position == s1.Length)) {
                                return type;
                            }
                        }
                    }
                }
                finally {
                    if ((s1 != null)) {
                        s1.Close();
                    }
                    if ((s2 != null)) {
                        s2.Close();
                    }
                }
            }
            xs.Add(dsSchema);
            return type;
        }
        
        public delegate void V_RESICARGORowChangeEventHandler(object sender, V_RESICARGORowChangeEvent e);
        
        /// <summary>
        ///Represents the strongly named DataTable class.
        ///</summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "2.0.0.0")]
        [global::System.Serializable()]
        [global::System.Xml.Serialization.XmlSchemaProviderAttribute("GetTypedTableSchema")]
        public partial class V_RESICARGODataTable : global::System.Data.TypedTableBase<V_RESICARGORow> {
            
            private global::System.Data.DataColumn columnNORESI;
            
            private global::System.Data.DataColumn columnASAL;
            
            private global::System.Data.DataColumn columnTUJUAN;
            
            private global::System.Data.DataColumn columnBERAT;
            
            private global::System.Data.DataColumn columnJUMLAH;
            
            private global::System.Data.DataColumn columnPENGIRIM;
            
            private global::System.Data.DataColumn columnALAMATPENGIRIM;
            
            private global::System.Data.DataColumn columnPHONEPENGIRIM;
            
            private global::System.Data.DataColumn columnPENERIMA;
            
            private global::System.Data.DataColumn columnALAMATPENERIMA;
            
            private global::System.Data.DataColumn columnPHONEPENERIMA;
            
            private global::System.Data.DataColumn columnLAYANAN;
            
            private global::System.Data.DataColumn columnHARGA;
            
            private global::System.Data.DataColumn columnJENISKIRIMAN;
            
            private global::System.Data.DataColumn columnASURANSI;
            
            private global::System.Data.DataColumn columnPPN;
            
            private global::System.Data.DataColumn columnJUMLAHTOTAL;
            
            private global::System.Data.DataColumn columnKETERANGANISI;
            
            private global::System.Data.DataColumn columnINSTRUKSIKHUSUS;
            
            private global::System.Data.DataColumn columnDIM_P;
            
            private global::System.Data.DataColumn columnDIM_L;
            
            private global::System.Data.DataColumn columnDIM_T;
            
            private global::System.Data.DataColumn columnHPPENGIRIM;
            
            private global::System.Data.DataColumn columnPACKING;
            
            private global::System.Data.DataColumn columnBARCODE;
            
            private global::System.Data.DataColumn columnNAMAPERUSAHAAN;
            
            private global::System.Data.DataColumn columnALAMATPERUSAHAAN;
            
            private global::System.Data.DataColumn columnTELPPERUSAHAAN;
            
            private global::System.Data.DataColumn columnFAXPERUSAHAAN;
            
            private global::System.Data.DataColumn columnTGLMANIFEST;
            
            private global::System.Data.DataColumn columnETD;
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public V_RESICARGODataTable() {
                this.TableName = "V_RESICARGO";
                this.BeginInit();
                this.InitClass();
                this.EndInit();
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            internal V_RESICARGODataTable(global::System.Data.DataTable table) {
                this.TableName = table.TableName;
                if ((table.CaseSensitive != table.DataSet.CaseSensitive)) {
                    this.CaseSensitive = table.CaseSensitive;
                }
                if ((table.Locale.ToString() != table.DataSet.Locale.ToString())) {
                    this.Locale = table.Locale;
                }
                if ((table.Namespace != table.DataSet.Namespace)) {
                    this.Namespace = table.Namespace;
                }
                this.Prefix = table.Prefix;
                this.MinimumCapacity = table.MinimumCapacity;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            protected V_RESICARGODataTable(global::System.Runtime.Serialization.SerializationInfo info, global::System.Runtime.Serialization.StreamingContext context) : 
                    base(info, context) {
                this.InitVars();
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn NORESIColumn {
                get {
                    return this.columnNORESI;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn ASALColumn {
                get {
                    return this.columnASAL;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn TUJUANColumn {
                get {
                    return this.columnTUJUAN;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn BERATColumn {
                get {
                    return this.columnBERAT;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn JUMLAHColumn {
                get {
                    return this.columnJUMLAH;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn PENGIRIMColumn {
                get {
                    return this.columnPENGIRIM;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn ALAMATPENGIRIMColumn {
                get {
                    return this.columnALAMATPENGIRIM;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn PHONEPENGIRIMColumn {
                get {
                    return this.columnPHONEPENGIRIM;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn PENERIMAColumn {
                get {
                    return this.columnPENERIMA;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn ALAMATPENERIMAColumn {
                get {
                    return this.columnALAMATPENERIMA;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn PHONEPENERIMAColumn {
                get {
                    return this.columnPHONEPENERIMA;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn LAYANANColumn {
                get {
                    return this.columnLAYANAN;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn HARGAColumn {
                get {
                    return this.columnHARGA;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn JENISKIRIMANColumn {
                get {
                    return this.columnJENISKIRIMAN;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn ASURANSIColumn {
                get {
                    return this.columnASURANSI;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn PPNColumn {
                get {
                    return this.columnPPN;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn JUMLAHTOTALColumn {
                get {
                    return this.columnJUMLAHTOTAL;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn KETERANGANISIColumn {
                get {
                    return this.columnKETERANGANISI;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn INSTRUKSIKHUSUSColumn {
                get {
                    return this.columnINSTRUKSIKHUSUS;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn DIM_PColumn {
                get {
                    return this.columnDIM_P;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn DIM_LColumn {
                get {
                    return this.columnDIM_L;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn DIM_TColumn {
                get {
                    return this.columnDIM_T;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn HPPENGIRIMColumn {
                get {
                    return this.columnHPPENGIRIM;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn PACKINGColumn {
                get {
                    return this.columnPACKING;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn BARCODEColumn {
                get {
                    return this.columnBARCODE;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn NAMAPERUSAHAANColumn {
                get {
                    return this.columnNAMAPERUSAHAAN;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn ALAMATPERUSAHAANColumn {
                get {
                    return this.columnALAMATPERUSAHAAN;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn TELPPERUSAHAANColumn {
                get {
                    return this.columnTELPPERUSAHAAN;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn FAXPERUSAHAANColumn {
                get {
                    return this.columnFAXPERUSAHAAN;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn TGLMANIFESTColumn {
                get {
                    return this.columnTGLMANIFEST;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn ETDColumn {
                get {
                    return this.columnETD;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.ComponentModel.Browsable(false)]
            public int Count {
                get {
                    return this.Rows.Count;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public V_RESICARGORow this[int index] {
                get {
                    return ((V_RESICARGORow)(this.Rows[index]));
                }
            }
            
            public event V_RESICARGORowChangeEventHandler V_RESICARGORowChanging;
            
            public event V_RESICARGORowChangeEventHandler V_RESICARGORowChanged;
            
            public event V_RESICARGORowChangeEventHandler V_RESICARGORowDeleting;
            
            public event V_RESICARGORowChangeEventHandler V_RESICARGORowDeleted;
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void AddV_RESICARGORow(V_RESICARGORow row) {
                this.Rows.Add(row);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public V_RESICARGORow AddV_RESICARGORow(
                        string NORESI, 
                        string ASAL, 
                        string TUJUAN, 
                        string BERAT, 
                        string JUMLAH, 
                        string PENGIRIM, 
                        string ALAMATPENGIRIM, 
                        string PHONEPENGIRIM, 
                        string PENERIMA, 
                        string ALAMATPENERIMA, 
                        string PHONEPENERIMA, 
                        string LAYANAN, 
                        string HARGA, 
                        string JENISKIRIMAN, 
                        string ASURANSI, 
                        string PPN, 
                        string JUMLAHTOTAL, 
                        string KETERANGANISI, 
                        string INSTRUKSIKHUSUS, 
                        string DIM_P, 
                        string DIM_L, 
                        string DIM_T, 
                        string HPPENGIRIM, 
                        string PACKING, 
                        string BARCODE, 
                        string NAMAPERUSAHAAN, 
                        string ALAMATPERUSAHAAN, 
                        string TELPPERUSAHAAN, 
                        string FAXPERUSAHAAN, 
                        string TGLMANIFEST, 
                        string ETD) {
                V_RESICARGORow rowV_RESICARGORow = ((V_RESICARGORow)(this.NewRow()));
                object[] columnValuesArray = new object[] {
                        NORESI,
                        ASAL,
                        TUJUAN,
                        BERAT,
                        JUMLAH,
                        PENGIRIM,
                        ALAMATPENGIRIM,
                        PHONEPENGIRIM,
                        PENERIMA,
                        ALAMATPENERIMA,
                        PHONEPENERIMA,
                        LAYANAN,
                        HARGA,
                        JENISKIRIMAN,
                        ASURANSI,
                        PPN,
                        JUMLAHTOTAL,
                        KETERANGANISI,
                        INSTRUKSIKHUSUS,
                        DIM_P,
                        DIM_L,
                        DIM_T,
                        HPPENGIRIM,
                        PACKING,
                        BARCODE,
                        NAMAPERUSAHAAN,
                        ALAMATPERUSAHAAN,
                        TELPPERUSAHAAN,
                        FAXPERUSAHAAN,
                        TGLMANIFEST,
                        ETD};
                rowV_RESICARGORow.ItemArray = columnValuesArray;
                this.Rows.Add(rowV_RESICARGORow);
                return rowV_RESICARGORow;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public override global::System.Data.DataTable Clone() {
                V_RESICARGODataTable cln = ((V_RESICARGODataTable)(base.Clone()));
                cln.InitVars();
                return cln;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            protected override global::System.Data.DataTable CreateInstance() {
                return new V_RESICARGODataTable();
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            internal void InitVars() {
                this.columnNORESI = base.Columns["NORESI"];
                this.columnASAL = base.Columns["ASAL"];
                this.columnTUJUAN = base.Columns["TUJUAN"];
                this.columnBERAT = base.Columns["BERAT"];
                this.columnJUMLAH = base.Columns["JUMLAH"];
                this.columnPENGIRIM = base.Columns["PENGIRIM"];
                this.columnALAMATPENGIRIM = base.Columns["ALAMATPENGIRIM"];
                this.columnPHONEPENGIRIM = base.Columns["PHONEPENGIRIM"];
                this.columnPENERIMA = base.Columns["PENERIMA"];
                this.columnALAMATPENERIMA = base.Columns["ALAMATPENERIMA"];
                this.columnPHONEPENERIMA = base.Columns["PHONEPENERIMA"];
                this.columnLAYANAN = base.Columns["LAYANAN"];
                this.columnHARGA = base.Columns["HARGA"];
                this.columnJENISKIRIMAN = base.Columns["JENISKIRIMAN"];
                this.columnASURANSI = base.Columns["ASURANSI"];
                this.columnPPN = base.Columns["PPN"];
                this.columnJUMLAHTOTAL = base.Columns["JUMLAHTOTAL"];
                this.columnKETERANGANISI = base.Columns["KETERANGANISI"];
                this.columnINSTRUKSIKHUSUS = base.Columns["INSTRUKSIKHUSUS"];
                this.columnDIM_P = base.Columns["DIM_P"];
                this.columnDIM_L = base.Columns["DIM_L"];
                this.columnDIM_T = base.Columns["DIM_T"];
                this.columnHPPENGIRIM = base.Columns["HPPENGIRIM"];
                this.columnPACKING = base.Columns["PACKING"];
                this.columnBARCODE = base.Columns["BARCODE"];
                this.columnNAMAPERUSAHAAN = base.Columns["NAMAPERUSAHAAN"];
                this.columnALAMATPERUSAHAAN = base.Columns["ALAMATPERUSAHAAN"];
                this.columnTELPPERUSAHAAN = base.Columns["TELPPERUSAHAAN"];
                this.columnFAXPERUSAHAAN = base.Columns["FAXPERUSAHAAN"];
                this.columnTGLMANIFEST = base.Columns["TGLMANIFEST"];
                this.columnETD = base.Columns["ETD"];
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            private void InitClass() {
                this.columnNORESI = new global::System.Data.DataColumn("NORESI", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnNORESI);
                this.columnASAL = new global::System.Data.DataColumn("ASAL", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnASAL);
                this.columnTUJUAN = new global::System.Data.DataColumn("TUJUAN", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnTUJUAN);
                this.columnBERAT = new global::System.Data.DataColumn("BERAT", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnBERAT);
                this.columnJUMLAH = new global::System.Data.DataColumn("JUMLAH", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnJUMLAH);
                this.columnPENGIRIM = new global::System.Data.DataColumn("PENGIRIM", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnPENGIRIM);
                this.columnALAMATPENGIRIM = new global::System.Data.DataColumn("ALAMATPENGIRIM", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnALAMATPENGIRIM);
                this.columnPHONEPENGIRIM = new global::System.Data.DataColumn("PHONEPENGIRIM", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnPHONEPENGIRIM);
                this.columnPENERIMA = new global::System.Data.DataColumn("PENERIMA", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnPENERIMA);
                this.columnALAMATPENERIMA = new global::System.Data.DataColumn("ALAMATPENERIMA", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnALAMATPENERIMA);
                this.columnPHONEPENERIMA = new global::System.Data.DataColumn("PHONEPENERIMA", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnPHONEPENERIMA);
                this.columnLAYANAN = new global::System.Data.DataColumn("LAYANAN", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnLAYANAN);
                this.columnHARGA = new global::System.Data.DataColumn("HARGA", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnHARGA);
                this.columnJENISKIRIMAN = new global::System.Data.DataColumn("JENISKIRIMAN", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnJENISKIRIMAN);
                this.columnASURANSI = new global::System.Data.DataColumn("ASURANSI", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnASURANSI);
                this.columnPPN = new global::System.Data.DataColumn("PPN", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnPPN);
                this.columnJUMLAHTOTAL = new global::System.Data.DataColumn("JUMLAHTOTAL", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnJUMLAHTOTAL);
                this.columnKETERANGANISI = new global::System.Data.DataColumn("KETERANGANISI", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnKETERANGANISI);
                this.columnINSTRUKSIKHUSUS = new global::System.Data.DataColumn("INSTRUKSIKHUSUS", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnINSTRUKSIKHUSUS);
                this.columnDIM_P = new global::System.Data.DataColumn("DIM_P", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnDIM_P);
                this.columnDIM_L = new global::System.Data.DataColumn("DIM_L", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnDIM_L);
                this.columnDIM_T = new global::System.Data.DataColumn("DIM_T", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnDIM_T);
                this.columnHPPENGIRIM = new global::System.Data.DataColumn("HPPENGIRIM", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnHPPENGIRIM);
                this.columnPACKING = new global::System.Data.DataColumn("PACKING", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnPACKING);
                this.columnBARCODE = new global::System.Data.DataColumn("BARCODE", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnBARCODE);
                this.columnNAMAPERUSAHAAN = new global::System.Data.DataColumn("NAMAPERUSAHAAN", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnNAMAPERUSAHAAN);
                this.columnALAMATPERUSAHAAN = new global::System.Data.DataColumn("ALAMATPERUSAHAAN", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnALAMATPERUSAHAAN);
                this.columnTELPPERUSAHAAN = new global::System.Data.DataColumn("TELPPERUSAHAAN", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnTELPPERUSAHAAN);
                this.columnFAXPERUSAHAAN = new global::System.Data.DataColumn("FAXPERUSAHAAN", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnFAXPERUSAHAAN);
                this.columnTGLMANIFEST = new global::System.Data.DataColumn("TGLMANIFEST", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnTGLMANIFEST);
                this.columnETD = new global::System.Data.DataColumn("ETD", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnETD);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public V_RESICARGORow NewV_RESICARGORow() {
                return ((V_RESICARGORow)(this.NewRow()));
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            protected override global::System.Data.DataRow NewRowFromBuilder(global::System.Data.DataRowBuilder builder) {
                return new V_RESICARGORow(builder);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            protected override global::System.Type GetRowType() {
                return typeof(V_RESICARGORow);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            protected override void OnRowChanged(global::System.Data.DataRowChangeEventArgs e) {
                base.OnRowChanged(e);
                if ((this.V_RESICARGORowChanged != null)) {
                    this.V_RESICARGORowChanged(this, new V_RESICARGORowChangeEvent(((V_RESICARGORow)(e.Row)), e.Action));
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            protected override void OnRowChanging(global::System.Data.DataRowChangeEventArgs e) {
                base.OnRowChanging(e);
                if ((this.V_RESICARGORowChanging != null)) {
                    this.V_RESICARGORowChanging(this, new V_RESICARGORowChangeEvent(((V_RESICARGORow)(e.Row)), e.Action));
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            protected override void OnRowDeleted(global::System.Data.DataRowChangeEventArgs e) {
                base.OnRowDeleted(e);
                if ((this.V_RESICARGORowDeleted != null)) {
                    this.V_RESICARGORowDeleted(this, new V_RESICARGORowChangeEvent(((V_RESICARGORow)(e.Row)), e.Action));
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            protected override void OnRowDeleting(global::System.Data.DataRowChangeEventArgs e) {
                base.OnRowDeleting(e);
                if ((this.V_RESICARGORowDeleting != null)) {
                    this.V_RESICARGORowDeleting(this, new V_RESICARGORowChangeEvent(((V_RESICARGORow)(e.Row)), e.Action));
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void RemoveV_RESICARGORow(V_RESICARGORow row) {
                this.Rows.Remove(row);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public static global::System.Xml.Schema.XmlSchemaComplexType GetTypedTableSchema(global::System.Xml.Schema.XmlSchemaSet xs) {
                global::System.Xml.Schema.XmlSchemaComplexType type = new global::System.Xml.Schema.XmlSchemaComplexType();
                global::System.Xml.Schema.XmlSchemaSequence sequence = new global::System.Xml.Schema.XmlSchemaSequence();
                dsRESICARGO ds = new dsRESICARGO();
                global::System.Xml.Schema.XmlSchemaAny any1 = new global::System.Xml.Schema.XmlSchemaAny();
                any1.Namespace = "http://www.w3.org/2001/XMLSchema";
                any1.MinOccurs = new decimal(0);
                any1.MaxOccurs = decimal.MaxValue;
                any1.ProcessContents = global::System.Xml.Schema.XmlSchemaContentProcessing.Lax;
                sequence.Items.Add(any1);
                global::System.Xml.Schema.XmlSchemaAny any2 = new global::System.Xml.Schema.XmlSchemaAny();
                any2.Namespace = "urn:schemas-microsoft-com:xml-diffgram-v1";
                any2.MinOccurs = new decimal(1);
                any2.ProcessContents = global::System.Xml.Schema.XmlSchemaContentProcessing.Lax;
                sequence.Items.Add(any2);
                global::System.Xml.Schema.XmlSchemaAttribute attribute1 = new global::System.Xml.Schema.XmlSchemaAttribute();
                attribute1.Name = "namespace";
                attribute1.FixedValue = ds.Namespace;
                type.Attributes.Add(attribute1);
                global::System.Xml.Schema.XmlSchemaAttribute attribute2 = new global::System.Xml.Schema.XmlSchemaAttribute();
                attribute2.Name = "tableTypeName";
                attribute2.FixedValue = "V_RESICARGODataTable";
                type.Attributes.Add(attribute2);
                type.Particle = sequence;
                global::System.Xml.Schema.XmlSchema dsSchema = ds.GetSchemaSerializable();
                if (xs.Contains(dsSchema.TargetNamespace)) {
                    global::System.IO.MemoryStream s1 = new global::System.IO.MemoryStream();
                    global::System.IO.MemoryStream s2 = new global::System.IO.MemoryStream();
                    try {
                        global::System.Xml.Schema.XmlSchema schema = null;
                        dsSchema.Write(s1);
                        for (global::System.Collections.IEnumerator schemas = xs.Schemas(dsSchema.TargetNamespace).GetEnumerator(); schemas.MoveNext(); ) {
                            schema = ((global::System.Xml.Schema.XmlSchema)(schemas.Current));
                            s2.SetLength(0);
                            schema.Write(s2);
                            if ((s1.Length == s2.Length)) {
                                s1.Position = 0;
                                s2.Position = 0;
                                for (; ((s1.Position != s1.Length) 
                                            && (s1.ReadByte() == s2.ReadByte())); ) {
                                    ;
                                }
                                if ((s1.Position == s1.Length)) {
                                    return type;
                                }
                            }
                        }
                    }
                    finally {
                        if ((s1 != null)) {
                            s1.Close();
                        }
                        if ((s2 != null)) {
                            s2.Close();
                        }
                    }
                }
                xs.Add(dsSchema);
                return type;
            }
        }
        
        /// <summary>
        ///Represents strongly named DataRow class.
        ///</summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "2.0.0.0")]
        public partial class V_RESICARGORow : global::System.Data.DataRow {
            
            private V_RESICARGODataTable tableV_RESICARGO;
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            internal V_RESICARGORow(global::System.Data.DataRowBuilder rb) : 
                    base(rb) {
                this.tableV_RESICARGO = ((V_RESICARGODataTable)(this.Table));
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public string NORESI {
                get {
                    try {
                        return ((string)(this[this.tableV_RESICARGO.NORESIColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'NORESI\' in table \'V_RESICARGO\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tableV_RESICARGO.NORESIColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public string ASAL {
                get {
                    try {
                        return ((string)(this[this.tableV_RESICARGO.ASALColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'ASAL\' in table \'V_RESICARGO\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tableV_RESICARGO.ASALColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public string TUJUAN {
                get {
                    try {
                        return ((string)(this[this.tableV_RESICARGO.TUJUANColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'TUJUAN\' in table \'V_RESICARGO\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tableV_RESICARGO.TUJUANColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public string BERAT {
                get {
                    try {
                        return ((string)(this[this.tableV_RESICARGO.BERATColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'BERAT\' in table \'V_RESICARGO\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tableV_RESICARGO.BERATColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public string JUMLAH {
                get {
                    try {
                        return ((string)(this[this.tableV_RESICARGO.JUMLAHColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'JUMLAH\' in table \'V_RESICARGO\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tableV_RESICARGO.JUMLAHColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public string PENGIRIM {
                get {
                    try {
                        return ((string)(this[this.tableV_RESICARGO.PENGIRIMColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'PENGIRIM\' in table \'V_RESICARGO\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tableV_RESICARGO.PENGIRIMColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public string ALAMATPENGIRIM {
                get {
                    try {
                        return ((string)(this[this.tableV_RESICARGO.ALAMATPENGIRIMColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'ALAMATPENGIRIM\' in table \'V_RESICARGO\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tableV_RESICARGO.ALAMATPENGIRIMColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public string PHONEPENGIRIM {
                get {
                    try {
                        return ((string)(this[this.tableV_RESICARGO.PHONEPENGIRIMColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'PHONEPENGIRIM\' in table \'V_RESICARGO\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tableV_RESICARGO.PHONEPENGIRIMColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public string PENERIMA {
                get {
                    try {
                        return ((string)(this[this.tableV_RESICARGO.PENERIMAColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'PENERIMA\' in table \'V_RESICARGO\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tableV_RESICARGO.PENERIMAColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public string ALAMATPENERIMA {
                get {
                    try {
                        return ((string)(this[this.tableV_RESICARGO.ALAMATPENERIMAColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'ALAMATPENERIMA\' in table \'V_RESICARGO\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tableV_RESICARGO.ALAMATPENERIMAColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public string PHONEPENERIMA {
                get {
                    try {
                        return ((string)(this[this.tableV_RESICARGO.PHONEPENERIMAColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'PHONEPENERIMA\' in table \'V_RESICARGO\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tableV_RESICARGO.PHONEPENERIMAColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public string LAYANAN {
                get {
                    try {
                        return ((string)(this[this.tableV_RESICARGO.LAYANANColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'LAYANAN\' in table \'V_RESICARGO\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tableV_RESICARGO.LAYANANColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public string HARGA {
                get {
                    try {
                        return ((string)(this[this.tableV_RESICARGO.HARGAColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'HARGA\' in table \'V_RESICARGO\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tableV_RESICARGO.HARGAColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public string JENISKIRIMAN {
                get {
                    try {
                        return ((string)(this[this.tableV_RESICARGO.JENISKIRIMANColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'JENISKIRIMAN\' in table \'V_RESICARGO\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tableV_RESICARGO.JENISKIRIMANColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public string ASURANSI {
                get {
                    try {
                        return ((string)(this[this.tableV_RESICARGO.ASURANSIColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'ASURANSI\' in table \'V_RESICARGO\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tableV_RESICARGO.ASURANSIColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public string PPN {
                get {
                    try {
                        return ((string)(this[this.tableV_RESICARGO.PPNColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'PPN\' in table \'V_RESICARGO\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tableV_RESICARGO.PPNColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public string JUMLAHTOTAL {
                get {
                    try {
                        return ((string)(this[this.tableV_RESICARGO.JUMLAHTOTALColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'JUMLAHTOTAL\' in table \'V_RESICARGO\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tableV_RESICARGO.JUMLAHTOTALColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public string KETERANGANISI {
                get {
                    try {
                        return ((string)(this[this.tableV_RESICARGO.KETERANGANISIColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'KETERANGANISI\' in table \'V_RESICARGO\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tableV_RESICARGO.KETERANGANISIColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public string INSTRUKSIKHUSUS {
                get {
                    try {
                        return ((string)(this[this.tableV_RESICARGO.INSTRUKSIKHUSUSColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'INSTRUKSIKHUSUS\' in table \'V_RESICARGO\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tableV_RESICARGO.INSTRUKSIKHUSUSColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public string DIM_P {
                get {
                    try {
                        return ((string)(this[this.tableV_RESICARGO.DIM_PColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'DIM_P\' in table \'V_RESICARGO\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tableV_RESICARGO.DIM_PColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public string DIM_L {
                get {
                    try {
                        return ((string)(this[this.tableV_RESICARGO.DIM_LColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'DIM_L\' in table \'V_RESICARGO\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tableV_RESICARGO.DIM_LColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public string DIM_T {
                get {
                    try {
                        return ((string)(this[this.tableV_RESICARGO.DIM_TColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'DIM_T\' in table \'V_RESICARGO\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tableV_RESICARGO.DIM_TColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public string HPPENGIRIM {
                get {
                    try {
                        return ((string)(this[this.tableV_RESICARGO.HPPENGIRIMColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'HPPENGIRIM\' in table \'V_RESICARGO\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tableV_RESICARGO.HPPENGIRIMColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public string PACKING {
                get {
                    try {
                        return ((string)(this[this.tableV_RESICARGO.PACKINGColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'PACKING\' in table \'V_RESICARGO\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tableV_RESICARGO.PACKINGColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public string BARCODE {
                get {
                    try {
                        return ((string)(this[this.tableV_RESICARGO.BARCODEColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'BARCODE\' in table \'V_RESICARGO\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tableV_RESICARGO.BARCODEColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public string NAMAPERUSAHAAN {
                get {
                    try {
                        return ((string)(this[this.tableV_RESICARGO.NAMAPERUSAHAANColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'NAMAPERUSAHAAN\' in table \'V_RESICARGO\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tableV_RESICARGO.NAMAPERUSAHAANColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public string ALAMATPERUSAHAAN {
                get {
                    try {
                        return ((string)(this[this.tableV_RESICARGO.ALAMATPERUSAHAANColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'ALAMATPERUSAHAAN\' in table \'V_RESICARGO\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tableV_RESICARGO.ALAMATPERUSAHAANColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public string TELPPERUSAHAAN {
                get {
                    try {
                        return ((string)(this[this.tableV_RESICARGO.TELPPERUSAHAANColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'TELPPERUSAHAAN\' in table \'V_RESICARGO\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tableV_RESICARGO.TELPPERUSAHAANColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public string FAXPERUSAHAAN {
                get {
                    try {
                        return ((string)(this[this.tableV_RESICARGO.FAXPERUSAHAANColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'FAXPERUSAHAAN\' in table \'V_RESICARGO\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tableV_RESICARGO.FAXPERUSAHAANColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public string TGLMANIFEST {
                get {
                    try {
                        return ((string)(this[this.tableV_RESICARGO.TGLMANIFESTColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'TGLMANIFEST\' in table \'V_RESICARGO\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tableV_RESICARGO.TGLMANIFESTColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public string ETD {
                get {
                    try {
                        return ((string)(this[this.tableV_RESICARGO.ETDColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'ETD\' in table \'V_RESICARGO\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tableV_RESICARGO.ETDColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IsNORESINull() {
                return this.IsNull(this.tableV_RESICARGO.NORESIColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetNORESINull() {
                this[this.tableV_RESICARGO.NORESIColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IsASALNull() {
                return this.IsNull(this.tableV_RESICARGO.ASALColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetASALNull() {
                this[this.tableV_RESICARGO.ASALColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IsTUJUANNull() {
                return this.IsNull(this.tableV_RESICARGO.TUJUANColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetTUJUANNull() {
                this[this.tableV_RESICARGO.TUJUANColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IsBERATNull() {
                return this.IsNull(this.tableV_RESICARGO.BERATColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetBERATNull() {
                this[this.tableV_RESICARGO.BERATColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IsJUMLAHNull() {
                return this.IsNull(this.tableV_RESICARGO.JUMLAHColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetJUMLAHNull() {
                this[this.tableV_RESICARGO.JUMLAHColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IsPENGIRIMNull() {
                return this.IsNull(this.tableV_RESICARGO.PENGIRIMColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetPENGIRIMNull() {
                this[this.tableV_RESICARGO.PENGIRIMColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IsALAMATPENGIRIMNull() {
                return this.IsNull(this.tableV_RESICARGO.ALAMATPENGIRIMColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetALAMATPENGIRIMNull() {
                this[this.tableV_RESICARGO.ALAMATPENGIRIMColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IsPHONEPENGIRIMNull() {
                return this.IsNull(this.tableV_RESICARGO.PHONEPENGIRIMColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetPHONEPENGIRIMNull() {
                this[this.tableV_RESICARGO.PHONEPENGIRIMColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IsPENERIMANull() {
                return this.IsNull(this.tableV_RESICARGO.PENERIMAColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetPENERIMANull() {
                this[this.tableV_RESICARGO.PENERIMAColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IsALAMATPENERIMANull() {
                return this.IsNull(this.tableV_RESICARGO.ALAMATPENERIMAColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetALAMATPENERIMANull() {
                this[this.tableV_RESICARGO.ALAMATPENERIMAColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IsPHONEPENERIMANull() {
                return this.IsNull(this.tableV_RESICARGO.PHONEPENERIMAColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetPHONEPENERIMANull() {
                this[this.tableV_RESICARGO.PHONEPENERIMAColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IsLAYANANNull() {
                return this.IsNull(this.tableV_RESICARGO.LAYANANColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetLAYANANNull() {
                this[this.tableV_RESICARGO.LAYANANColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IsHARGANull() {
                return this.IsNull(this.tableV_RESICARGO.HARGAColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetHARGANull() {
                this[this.tableV_RESICARGO.HARGAColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IsJENISKIRIMANNull() {
                return this.IsNull(this.tableV_RESICARGO.JENISKIRIMANColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetJENISKIRIMANNull() {
                this[this.tableV_RESICARGO.JENISKIRIMANColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IsASURANSINull() {
                return this.IsNull(this.tableV_RESICARGO.ASURANSIColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetASURANSINull() {
                this[this.tableV_RESICARGO.ASURANSIColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IsPPNNull() {
                return this.IsNull(this.tableV_RESICARGO.PPNColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetPPNNull() {
                this[this.tableV_RESICARGO.PPNColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IsJUMLAHTOTALNull() {
                return this.IsNull(this.tableV_RESICARGO.JUMLAHTOTALColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetJUMLAHTOTALNull() {
                this[this.tableV_RESICARGO.JUMLAHTOTALColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IsKETERANGANISINull() {
                return this.IsNull(this.tableV_RESICARGO.KETERANGANISIColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetKETERANGANISINull() {
                this[this.tableV_RESICARGO.KETERANGANISIColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IsINSTRUKSIKHUSUSNull() {
                return this.IsNull(this.tableV_RESICARGO.INSTRUKSIKHUSUSColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetINSTRUKSIKHUSUSNull() {
                this[this.tableV_RESICARGO.INSTRUKSIKHUSUSColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IsDIM_PNull() {
                return this.IsNull(this.tableV_RESICARGO.DIM_PColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetDIM_PNull() {
                this[this.tableV_RESICARGO.DIM_PColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IsDIM_LNull() {
                return this.IsNull(this.tableV_RESICARGO.DIM_LColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetDIM_LNull() {
                this[this.tableV_RESICARGO.DIM_LColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IsDIM_TNull() {
                return this.IsNull(this.tableV_RESICARGO.DIM_TColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetDIM_TNull() {
                this[this.tableV_RESICARGO.DIM_TColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IsHPPENGIRIMNull() {
                return this.IsNull(this.tableV_RESICARGO.HPPENGIRIMColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetHPPENGIRIMNull() {
                this[this.tableV_RESICARGO.HPPENGIRIMColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IsPACKINGNull() {
                return this.IsNull(this.tableV_RESICARGO.PACKINGColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetPACKINGNull() {
                this[this.tableV_RESICARGO.PACKINGColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IsBARCODENull() {
                return this.IsNull(this.tableV_RESICARGO.BARCODEColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetBARCODENull() {
                this[this.tableV_RESICARGO.BARCODEColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IsNAMAPERUSAHAANNull() {
                return this.IsNull(this.tableV_RESICARGO.NAMAPERUSAHAANColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetNAMAPERUSAHAANNull() {
                this[this.tableV_RESICARGO.NAMAPERUSAHAANColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IsALAMATPERUSAHAANNull() {
                return this.IsNull(this.tableV_RESICARGO.ALAMATPERUSAHAANColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetALAMATPERUSAHAANNull() {
                this[this.tableV_RESICARGO.ALAMATPERUSAHAANColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IsTELPPERUSAHAANNull() {
                return this.IsNull(this.tableV_RESICARGO.TELPPERUSAHAANColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetTELPPERUSAHAANNull() {
                this[this.tableV_RESICARGO.TELPPERUSAHAANColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IsFAXPERUSAHAANNull() {
                return this.IsNull(this.tableV_RESICARGO.FAXPERUSAHAANColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetFAXPERUSAHAANNull() {
                this[this.tableV_RESICARGO.FAXPERUSAHAANColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IsTGLMANIFESTNull() {
                return this.IsNull(this.tableV_RESICARGO.TGLMANIFESTColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetTGLMANIFESTNull() {
                this[this.tableV_RESICARGO.TGLMANIFESTColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IsETDNull() {
                return this.IsNull(this.tableV_RESICARGO.ETDColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetETDNull() {
                this[this.tableV_RESICARGO.ETDColumn] = global::System.Convert.DBNull;
            }
        }
        
        /// <summary>
        ///Row event argument class
        ///</summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "2.0.0.0")]
        public class V_RESICARGORowChangeEvent : global::System.EventArgs {
            
            private V_RESICARGORow eventRow;
            
            private global::System.Data.DataRowAction eventAction;
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public V_RESICARGORowChangeEvent(V_RESICARGORow row, global::System.Data.DataRowAction action) {
                this.eventRow = row;
                this.eventAction = action;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public V_RESICARGORow Row {
                get {
                    return this.eventRow;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataRowAction Action {
                get {
                    return this.eventAction;
                }
            }
        }
    }
}

#pragma warning restore 1591