//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3053
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

#pragma warning disable 1591

namespace LOGISTICMANAGAMENTSYSTEM.REPORTS.EXPRESS {
    
    
    /// <summary>
    ///Represents a strongly typed in-memory cache of data.
    ///</summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "2.0.0.0")]
    [global::System.Serializable()]
    [global::System.ComponentModel.DesignerCategoryAttribute("code")]
    [global::System.ComponentModel.ToolboxItem(true)]
    [global::System.Xml.Serialization.XmlSchemaProviderAttribute("GetTypedDataSetSchema")]
    [global::System.Xml.Serialization.XmlRootAttribute("dsCOURIER")]
    [global::System.ComponentModel.Design.HelpKeywordAttribute("vs.data.DataSet")]
    public partial class dsCOURIER : global::System.Data.DataSet {
        
        private v_courierDataTable tablev_courier;
        
        private global::System.Data.SchemaSerializationMode _schemaSerializationMode = global::System.Data.SchemaSerializationMode.IncludeSchema;
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public dsCOURIER() {
            this.BeginInit();
            this.InitClass();
            global::System.ComponentModel.CollectionChangeEventHandler schemaChangedHandler = new global::System.ComponentModel.CollectionChangeEventHandler(this.SchemaChanged);
            base.Tables.CollectionChanged += schemaChangedHandler;
            base.Relations.CollectionChanged += schemaChangedHandler;
            this.EndInit();
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        protected dsCOURIER(global::System.Runtime.Serialization.SerializationInfo info, global::System.Runtime.Serialization.StreamingContext context) : 
                base(info, context, false) {
            if ((this.IsBinarySerialized(info, context) == true)) {
                this.InitVars(false);
                global::System.ComponentModel.CollectionChangeEventHandler schemaChangedHandler1 = new global::System.ComponentModel.CollectionChangeEventHandler(this.SchemaChanged);
                this.Tables.CollectionChanged += schemaChangedHandler1;
                this.Relations.CollectionChanged += schemaChangedHandler1;
                return;
            }
            string strSchema = ((string)(info.GetValue("XmlSchema", typeof(string))));
            if ((this.DetermineSchemaSerializationMode(info, context) == global::System.Data.SchemaSerializationMode.IncludeSchema)) {
                global::System.Data.DataSet ds = new global::System.Data.DataSet();
                ds.ReadXmlSchema(new global::System.Xml.XmlTextReader(new global::System.IO.StringReader(strSchema)));
                if ((ds.Tables["v_courier"] != null)) {
                    base.Tables.Add(new v_courierDataTable(ds.Tables["v_courier"]));
                }
                this.DataSetName = ds.DataSetName;
                this.Prefix = ds.Prefix;
                this.Namespace = ds.Namespace;
                this.Locale = ds.Locale;
                this.CaseSensitive = ds.CaseSensitive;
                this.EnforceConstraints = ds.EnforceConstraints;
                this.Merge(ds, false, global::System.Data.MissingSchemaAction.Add);
                this.InitVars();
            }
            else {
                this.ReadXmlSchema(new global::System.Xml.XmlTextReader(new global::System.IO.StringReader(strSchema)));
            }
            this.GetSerializationData(info, context);
            global::System.ComponentModel.CollectionChangeEventHandler schemaChangedHandler = new global::System.ComponentModel.CollectionChangeEventHandler(this.SchemaChanged);
            base.Tables.CollectionChanged += schemaChangedHandler;
            this.Relations.CollectionChanged += schemaChangedHandler;
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.ComponentModel.Browsable(false)]
        [global::System.ComponentModel.DesignerSerializationVisibility(global::System.ComponentModel.DesignerSerializationVisibility.Content)]
        public v_courierDataTable v_courier {
            get {
                return this.tablev_courier;
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.ComponentModel.BrowsableAttribute(true)]
        [global::System.ComponentModel.DesignerSerializationVisibilityAttribute(global::System.ComponentModel.DesignerSerializationVisibility.Visible)]
        public override global::System.Data.SchemaSerializationMode SchemaSerializationMode {
            get {
                return this._schemaSerializationMode;
            }
            set {
                this._schemaSerializationMode = value;
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.ComponentModel.DesignerSerializationVisibilityAttribute(global::System.ComponentModel.DesignerSerializationVisibility.Hidden)]
        public new global::System.Data.DataTableCollection Tables {
            get {
                return base.Tables;
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.ComponentModel.DesignerSerializationVisibilityAttribute(global::System.ComponentModel.DesignerSerializationVisibility.Hidden)]
        public new global::System.Data.DataRelationCollection Relations {
            get {
                return base.Relations;
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        protected override void InitializeDerivedDataSet() {
            this.BeginInit();
            this.InitClass();
            this.EndInit();
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public override global::System.Data.DataSet Clone() {
            dsCOURIER cln = ((dsCOURIER)(base.Clone()));
            cln.InitVars();
            cln.SchemaSerializationMode = this.SchemaSerializationMode;
            return cln;
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        protected override bool ShouldSerializeTables() {
            return false;
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        protected override bool ShouldSerializeRelations() {
            return false;
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        protected override void ReadXmlSerializable(global::System.Xml.XmlReader reader) {
            if ((this.DetermineSchemaSerializationMode(reader) == global::System.Data.SchemaSerializationMode.IncludeSchema)) {
                this.Reset();
                global::System.Data.DataSet ds = new global::System.Data.DataSet();
                ds.ReadXml(reader);
                if ((ds.Tables["v_courier"] != null)) {
                    base.Tables.Add(new v_courierDataTable(ds.Tables["v_courier"]));
                }
                this.DataSetName = ds.DataSetName;
                this.Prefix = ds.Prefix;
                this.Namespace = ds.Namespace;
                this.Locale = ds.Locale;
                this.CaseSensitive = ds.CaseSensitive;
                this.EnforceConstraints = ds.EnforceConstraints;
                this.Merge(ds, false, global::System.Data.MissingSchemaAction.Add);
                this.InitVars();
            }
            else {
                this.ReadXml(reader);
                this.InitVars();
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        protected override global::System.Xml.Schema.XmlSchema GetSchemaSerializable() {
            global::System.IO.MemoryStream stream = new global::System.IO.MemoryStream();
            this.WriteXmlSchema(new global::System.Xml.XmlTextWriter(stream, null));
            stream.Position = 0;
            return global::System.Xml.Schema.XmlSchema.Read(new global::System.Xml.XmlTextReader(stream), null);
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        internal void InitVars() {
            this.InitVars(true);
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        internal void InitVars(bool initTable) {
            this.tablev_courier = ((v_courierDataTable)(base.Tables["v_courier"]));
            if ((initTable == true)) {
                if ((this.tablev_courier != null)) {
                    this.tablev_courier.InitVars();
                }
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private void InitClass() {
            this.DataSetName = "dsCOURIER";
            this.Prefix = "";
            this.Namespace = "http://tempuri.org/dsCOURIER.xsd";
            this.EnforceConstraints = true;
            this.SchemaSerializationMode = global::System.Data.SchemaSerializationMode.IncludeSchema;
            this.tablev_courier = new v_courierDataTable();
            base.Tables.Add(this.tablev_courier);
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private bool ShouldSerializev_courier() {
            return false;
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private void SchemaChanged(object sender, global::System.ComponentModel.CollectionChangeEventArgs e) {
            if ((e.Action == global::System.ComponentModel.CollectionChangeAction.Remove)) {
                this.InitVars();
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public static global::System.Xml.Schema.XmlSchemaComplexType GetTypedDataSetSchema(global::System.Xml.Schema.XmlSchemaSet xs) {
            dsCOURIER ds = new dsCOURIER();
            global::System.Xml.Schema.XmlSchemaComplexType type = new global::System.Xml.Schema.XmlSchemaComplexType();
            global::System.Xml.Schema.XmlSchemaSequence sequence = new global::System.Xml.Schema.XmlSchemaSequence();
            global::System.Xml.Schema.XmlSchemaAny any = new global::System.Xml.Schema.XmlSchemaAny();
            any.Namespace = ds.Namespace;
            sequence.Items.Add(any);
            type.Particle = sequence;
            global::System.Xml.Schema.XmlSchema dsSchema = ds.GetSchemaSerializable();
            if (xs.Contains(dsSchema.TargetNamespace)) {
                global::System.IO.MemoryStream s1 = new global::System.IO.MemoryStream();
                global::System.IO.MemoryStream s2 = new global::System.IO.MemoryStream();
                try {
                    global::System.Xml.Schema.XmlSchema schema = null;
                    dsSchema.Write(s1);
                    for (global::System.Collections.IEnumerator schemas = xs.Schemas(dsSchema.TargetNamespace).GetEnumerator(); schemas.MoveNext(); ) {
                        schema = ((global::System.Xml.Schema.XmlSchema)(schemas.Current));
                        s2.SetLength(0);
                        schema.Write(s2);
                        if ((s1.Length == s2.Length)) {
                            s1.Position = 0;
                            s2.Position = 0;
                            for (; ((s1.Position != s1.Length) 
                                        && (s1.ReadByte() == s2.ReadByte())); ) {
                                ;
                            }
                            if ((s1.Position == s1.Length)) {
                                return type;
                            }
                        }
                    }
                }
                finally {
                    if ((s1 != null)) {
                        s1.Close();
                    }
                    if ((s2 != null)) {
                        s2.Close();
                    }
                }
            }
            xs.Add(dsSchema);
            return type;
        }
        
        public delegate void v_courierRowChangeEventHandler(object sender, v_courierRowChangeEvent e);
        
        /// <summary>
        ///Represents the strongly named DataTable class.
        ///</summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "2.0.0.0")]
        [global::System.Serializable()]
        [global::System.Xml.Serialization.XmlSchemaProviderAttribute("GetTypedTableSchema")]
        public partial class v_courierDataTable : global::System.Data.TypedTableBase<v_courierRow> {
            
            private global::System.Data.DataColumn columnNO;
            
            private global::System.Data.DataColumn columnSTARTDATE;
            
            private global::System.Data.DataColumn columnENDDATE;
            
            private global::System.Data.DataColumn columnTGLTERIMA;
            
            private global::System.Data.DataColumn columnCUSTOMER;
            
            private global::System.Data.DataColumn columnASAL;
            
            private global::System.Data.DataColumn columnTUJUAN;
            
            private global::System.Data.DataColumn columnPENERIMA;
            
            private global::System.Data.DataColumn columnSERVICE;
            
            private global::System.Data.DataColumn columnJENISKIRIMAN;
            
            private global::System.Data.DataColumn columnJUMLAH;
            
            private global::System.Data.DataColumn columnBERAT;
            
            private global::System.Data.DataColumn columnCHARGE;
            
            private global::System.Data.DataColumn columnOTHERCHARGE;
            
            private global::System.Data.DataColumn columnDISKON;
            
            private global::System.Data.DataColumn columnTOTAL;
            
            private global::System.Data.DataColumn columnSTATUS;
            
            private global::System.Data.DataColumn columnNAMAPERUSAHAAN;
            
            private global::System.Data.DataColumn columnALAMATPERUSAHAAN;
            
            private global::System.Data.DataColumn columnTELPPERUSAHAAN;
            
            private global::System.Data.DataColumn columnFAXPERUSAHAAN;
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public v_courierDataTable() {
                this.TableName = "v_courier";
                this.BeginInit();
                this.InitClass();
                this.EndInit();
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            internal v_courierDataTable(global::System.Data.DataTable table) {
                this.TableName = table.TableName;
                if ((table.CaseSensitive != table.DataSet.CaseSensitive)) {
                    this.CaseSensitive = table.CaseSensitive;
                }
                if ((table.Locale.ToString() != table.DataSet.Locale.ToString())) {
                    this.Locale = table.Locale;
                }
                if ((table.Namespace != table.DataSet.Namespace)) {
                    this.Namespace = table.Namespace;
                }
                this.Prefix = table.Prefix;
                this.MinimumCapacity = table.MinimumCapacity;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            protected v_courierDataTable(global::System.Runtime.Serialization.SerializationInfo info, global::System.Runtime.Serialization.StreamingContext context) : 
                    base(info, context) {
                this.InitVars();
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn NOColumn {
                get {
                    return this.columnNO;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn STARTDATEColumn {
                get {
                    return this.columnSTARTDATE;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn ENDDATEColumn {
                get {
                    return this.columnENDDATE;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn TGLTERIMAColumn {
                get {
                    return this.columnTGLTERIMA;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn CUSTOMERColumn {
                get {
                    return this.columnCUSTOMER;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn ASALColumn {
                get {
                    return this.columnASAL;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn TUJUANColumn {
                get {
                    return this.columnTUJUAN;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn PENERIMAColumn {
                get {
                    return this.columnPENERIMA;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn SERVICEColumn {
                get {
                    return this.columnSERVICE;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn JENISKIRIMANColumn {
                get {
                    return this.columnJENISKIRIMAN;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn JUMLAHColumn {
                get {
                    return this.columnJUMLAH;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn BERATColumn {
                get {
                    return this.columnBERAT;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn CHARGEColumn {
                get {
                    return this.columnCHARGE;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn OTHERCHARGEColumn {
                get {
                    return this.columnOTHERCHARGE;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn DISKONColumn {
                get {
                    return this.columnDISKON;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn TOTALColumn {
                get {
                    return this.columnTOTAL;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn STATUSColumn {
                get {
                    return this.columnSTATUS;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn NAMAPERUSAHAANColumn {
                get {
                    return this.columnNAMAPERUSAHAAN;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn ALAMATPERUSAHAANColumn {
                get {
                    return this.columnALAMATPERUSAHAAN;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn TELPPERUSAHAANColumn {
                get {
                    return this.columnTELPPERUSAHAAN;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn FAXPERUSAHAANColumn {
                get {
                    return this.columnFAXPERUSAHAAN;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.ComponentModel.Browsable(false)]
            public int Count {
                get {
                    return this.Rows.Count;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public v_courierRow this[int index] {
                get {
                    return ((v_courierRow)(this.Rows[index]));
                }
            }
            
            public event v_courierRowChangeEventHandler v_courierRowChanging;
            
            public event v_courierRowChangeEventHandler v_courierRowChanged;
            
            public event v_courierRowChangeEventHandler v_courierRowDeleting;
            
            public event v_courierRowChangeEventHandler v_courierRowDeleted;
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void Addv_courierRow(v_courierRow row) {
                this.Rows.Add(row);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public v_courierRow Addv_courierRow(
                        string NO, 
                        string STARTDATE, 
                        string ENDDATE, 
                        string TGLTERIMA, 
                        string CUSTOMER, 
                        string ASAL, 
                        string TUJUAN, 
                        string PENERIMA, 
                        string SERVICE, 
                        string JENISKIRIMAN, 
                        string JUMLAH, 
                        string BERAT, 
                        string CHARGE, 
                        string OTHERCHARGE, 
                        string DISKON, 
                        string TOTAL, 
                        string STATUS, 
                        string NAMAPERUSAHAAN, 
                        string ALAMATPERUSAHAAN, 
                        string TELPPERUSAHAAN, 
                        string FAXPERUSAHAAN) {
                v_courierRow rowv_courierRow = ((v_courierRow)(this.NewRow()));
                object[] columnValuesArray = new object[] {
                        NO,
                        STARTDATE,
                        ENDDATE,
                        TGLTERIMA,
                        CUSTOMER,
                        ASAL,
                        TUJUAN,
                        PENERIMA,
                        SERVICE,
                        JENISKIRIMAN,
                        JUMLAH,
                        BERAT,
                        CHARGE,
                        OTHERCHARGE,
                        DISKON,
                        TOTAL,
                        STATUS,
                        NAMAPERUSAHAAN,
                        ALAMATPERUSAHAAN,
                        TELPPERUSAHAAN,
                        FAXPERUSAHAAN};
                rowv_courierRow.ItemArray = columnValuesArray;
                this.Rows.Add(rowv_courierRow);
                return rowv_courierRow;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public override global::System.Data.DataTable Clone() {
                v_courierDataTable cln = ((v_courierDataTable)(base.Clone()));
                cln.InitVars();
                return cln;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            protected override global::System.Data.DataTable CreateInstance() {
                return new v_courierDataTable();
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            internal void InitVars() {
                this.columnNO = base.Columns["NO"];
                this.columnSTARTDATE = base.Columns["STARTDATE"];
                this.columnENDDATE = base.Columns["ENDDATE"];
                this.columnTGLTERIMA = base.Columns["TGLTERIMA"];
                this.columnCUSTOMER = base.Columns["CUSTOMER"];
                this.columnASAL = base.Columns["ASAL"];
                this.columnTUJUAN = base.Columns["TUJUAN"];
                this.columnPENERIMA = base.Columns["PENERIMA"];
                this.columnSERVICE = base.Columns["SERVICE"];
                this.columnJENISKIRIMAN = base.Columns["JENISKIRIMAN"];
                this.columnJUMLAH = base.Columns["JUMLAH"];
                this.columnBERAT = base.Columns["BERAT"];
                this.columnCHARGE = base.Columns["CHARGE"];
                this.columnOTHERCHARGE = base.Columns["OTHERCHARGE"];
                this.columnDISKON = base.Columns["DISKON"];
                this.columnTOTAL = base.Columns["TOTAL"];
                this.columnSTATUS = base.Columns["STATUS"];
                this.columnNAMAPERUSAHAAN = base.Columns["NAMAPERUSAHAAN"];
                this.columnALAMATPERUSAHAAN = base.Columns["ALAMATPERUSAHAAN"];
                this.columnTELPPERUSAHAAN = base.Columns["TELPPERUSAHAAN"];
                this.columnFAXPERUSAHAAN = base.Columns["FAXPERUSAHAAN"];
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            private void InitClass() {
                this.columnNO = new global::System.Data.DataColumn("NO", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnNO);
                this.columnSTARTDATE = new global::System.Data.DataColumn("STARTDATE", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnSTARTDATE);
                this.columnENDDATE = new global::System.Data.DataColumn("ENDDATE", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnENDDATE);
                this.columnTGLTERIMA = new global::System.Data.DataColumn("TGLTERIMA", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnTGLTERIMA);
                this.columnCUSTOMER = new global::System.Data.DataColumn("CUSTOMER", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnCUSTOMER);
                this.columnASAL = new global::System.Data.DataColumn("ASAL", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnASAL);
                this.columnTUJUAN = new global::System.Data.DataColumn("TUJUAN", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnTUJUAN);
                this.columnPENERIMA = new global::System.Data.DataColumn("PENERIMA", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnPENERIMA);
                this.columnSERVICE = new global::System.Data.DataColumn("SERVICE", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnSERVICE);
                this.columnJENISKIRIMAN = new global::System.Data.DataColumn("JENISKIRIMAN", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnJENISKIRIMAN);
                this.columnJUMLAH = new global::System.Data.DataColumn("JUMLAH", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnJUMLAH);
                this.columnBERAT = new global::System.Data.DataColumn("BERAT", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnBERAT);
                this.columnCHARGE = new global::System.Data.DataColumn("CHARGE", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnCHARGE);
                this.columnOTHERCHARGE = new global::System.Data.DataColumn("OTHERCHARGE", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnOTHERCHARGE);
                this.columnDISKON = new global::System.Data.DataColumn("DISKON", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnDISKON);
                this.columnTOTAL = new global::System.Data.DataColumn("TOTAL", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnTOTAL);
                this.columnSTATUS = new global::System.Data.DataColumn("STATUS", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnSTATUS);
                this.columnNAMAPERUSAHAAN = new global::System.Data.DataColumn("NAMAPERUSAHAAN", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnNAMAPERUSAHAAN);
                this.columnALAMATPERUSAHAAN = new global::System.Data.DataColumn("ALAMATPERUSAHAAN", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnALAMATPERUSAHAAN);
                this.columnTELPPERUSAHAAN = new global::System.Data.DataColumn("TELPPERUSAHAAN", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnTELPPERUSAHAAN);
                this.columnFAXPERUSAHAAN = new global::System.Data.DataColumn("FAXPERUSAHAAN", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnFAXPERUSAHAAN);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public v_courierRow Newv_courierRow() {
                return ((v_courierRow)(this.NewRow()));
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            protected override global::System.Data.DataRow NewRowFromBuilder(global::System.Data.DataRowBuilder builder) {
                return new v_courierRow(builder);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            protected override global::System.Type GetRowType() {
                return typeof(v_courierRow);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            protected override void OnRowChanged(global::System.Data.DataRowChangeEventArgs e) {
                base.OnRowChanged(e);
                if ((this.v_courierRowChanged != null)) {
                    this.v_courierRowChanged(this, new v_courierRowChangeEvent(((v_courierRow)(e.Row)), e.Action));
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            protected override void OnRowChanging(global::System.Data.DataRowChangeEventArgs e) {
                base.OnRowChanging(e);
                if ((this.v_courierRowChanging != null)) {
                    this.v_courierRowChanging(this, new v_courierRowChangeEvent(((v_courierRow)(e.Row)), e.Action));
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            protected override void OnRowDeleted(global::System.Data.DataRowChangeEventArgs e) {
                base.OnRowDeleted(e);
                if ((this.v_courierRowDeleted != null)) {
                    this.v_courierRowDeleted(this, new v_courierRowChangeEvent(((v_courierRow)(e.Row)), e.Action));
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            protected override void OnRowDeleting(global::System.Data.DataRowChangeEventArgs e) {
                base.OnRowDeleting(e);
                if ((this.v_courierRowDeleting != null)) {
                    this.v_courierRowDeleting(this, new v_courierRowChangeEvent(((v_courierRow)(e.Row)), e.Action));
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void Removev_courierRow(v_courierRow row) {
                this.Rows.Remove(row);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public static global::System.Xml.Schema.XmlSchemaComplexType GetTypedTableSchema(global::System.Xml.Schema.XmlSchemaSet xs) {
                global::System.Xml.Schema.XmlSchemaComplexType type = new global::System.Xml.Schema.XmlSchemaComplexType();
                global::System.Xml.Schema.XmlSchemaSequence sequence = new global::System.Xml.Schema.XmlSchemaSequence();
                dsCOURIER ds = new dsCOURIER();
                global::System.Xml.Schema.XmlSchemaAny any1 = new global::System.Xml.Schema.XmlSchemaAny();
                any1.Namespace = "http://www.w3.org/2001/XMLSchema";
                any1.MinOccurs = new decimal(0);
                any1.MaxOccurs = decimal.MaxValue;
                any1.ProcessContents = global::System.Xml.Schema.XmlSchemaContentProcessing.Lax;
                sequence.Items.Add(any1);
                global::System.Xml.Schema.XmlSchemaAny any2 = new global::System.Xml.Schema.XmlSchemaAny();
                any2.Namespace = "urn:schemas-microsoft-com:xml-diffgram-v1";
                any2.MinOccurs = new decimal(1);
                any2.ProcessContents = global::System.Xml.Schema.XmlSchemaContentProcessing.Lax;
                sequence.Items.Add(any2);
                global::System.Xml.Schema.XmlSchemaAttribute attribute1 = new global::System.Xml.Schema.XmlSchemaAttribute();
                attribute1.Name = "namespace";
                attribute1.FixedValue = ds.Namespace;
                type.Attributes.Add(attribute1);
                global::System.Xml.Schema.XmlSchemaAttribute attribute2 = new global::System.Xml.Schema.XmlSchemaAttribute();
                attribute2.Name = "tableTypeName";
                attribute2.FixedValue = "v_courierDataTable";
                type.Attributes.Add(attribute2);
                type.Particle = sequence;
                global::System.Xml.Schema.XmlSchema dsSchema = ds.GetSchemaSerializable();
                if (xs.Contains(dsSchema.TargetNamespace)) {
                    global::System.IO.MemoryStream s1 = new global::System.IO.MemoryStream();
                    global::System.IO.MemoryStream s2 = new global::System.IO.MemoryStream();
                    try {
                        global::System.Xml.Schema.XmlSchema schema = null;
                        dsSchema.Write(s1);
                        for (global::System.Collections.IEnumerator schemas = xs.Schemas(dsSchema.TargetNamespace).GetEnumerator(); schemas.MoveNext(); ) {
                            schema = ((global::System.Xml.Schema.XmlSchema)(schemas.Current));
                            s2.SetLength(0);
                            schema.Write(s2);
                            if ((s1.Length == s2.Length)) {
                                s1.Position = 0;
                                s2.Position = 0;
                                for (; ((s1.Position != s1.Length) 
                                            && (s1.ReadByte() == s2.ReadByte())); ) {
                                    ;
                                }
                                if ((s1.Position == s1.Length)) {
                                    return type;
                                }
                            }
                        }
                    }
                    finally {
                        if ((s1 != null)) {
                            s1.Close();
                        }
                        if ((s2 != null)) {
                            s2.Close();
                        }
                    }
                }
                xs.Add(dsSchema);
                return type;
            }
        }
        
        /// <summary>
        ///Represents strongly named DataRow class.
        ///</summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "2.0.0.0")]
        public partial class v_courierRow : global::System.Data.DataRow {
            
            private v_courierDataTable tablev_courier;
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            internal v_courierRow(global::System.Data.DataRowBuilder rb) : 
                    base(rb) {
                this.tablev_courier = ((v_courierDataTable)(this.Table));
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public string NO {
                get {
                    try {
                        return ((string)(this[this.tablev_courier.NOColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'NO\' in table \'v_courier\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tablev_courier.NOColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public string STARTDATE {
                get {
                    try {
                        return ((string)(this[this.tablev_courier.STARTDATEColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'STARTDATE\' in table \'v_courier\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tablev_courier.STARTDATEColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public string ENDDATE {
                get {
                    try {
                        return ((string)(this[this.tablev_courier.ENDDATEColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'ENDDATE\' in table \'v_courier\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tablev_courier.ENDDATEColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public string TGLTERIMA {
                get {
                    try {
                        return ((string)(this[this.tablev_courier.TGLTERIMAColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'TGLTERIMA\' in table \'v_courier\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tablev_courier.TGLTERIMAColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public string CUSTOMER {
                get {
                    try {
                        return ((string)(this[this.tablev_courier.CUSTOMERColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'CUSTOMER\' in table \'v_courier\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tablev_courier.CUSTOMERColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public string ASAL {
                get {
                    try {
                        return ((string)(this[this.tablev_courier.ASALColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'ASAL\' in table \'v_courier\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tablev_courier.ASALColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public string TUJUAN {
                get {
                    try {
                        return ((string)(this[this.tablev_courier.TUJUANColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'TUJUAN\' in table \'v_courier\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tablev_courier.TUJUANColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public string PENERIMA {
                get {
                    try {
                        return ((string)(this[this.tablev_courier.PENERIMAColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'PENERIMA\' in table \'v_courier\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tablev_courier.PENERIMAColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public string SERVICE {
                get {
                    try {
                        return ((string)(this[this.tablev_courier.SERVICEColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'SERVICE\' in table \'v_courier\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tablev_courier.SERVICEColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public string JENISKIRIMAN {
                get {
                    try {
                        return ((string)(this[this.tablev_courier.JENISKIRIMANColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'JENISKIRIMAN\' in table \'v_courier\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tablev_courier.JENISKIRIMANColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public string JUMLAH {
                get {
                    try {
                        return ((string)(this[this.tablev_courier.JUMLAHColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'JUMLAH\' in table \'v_courier\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tablev_courier.JUMLAHColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public string BERAT {
                get {
                    try {
                        return ((string)(this[this.tablev_courier.BERATColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'BERAT\' in table \'v_courier\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tablev_courier.BERATColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public string CHARGE {
                get {
                    try {
                        return ((string)(this[this.tablev_courier.CHARGEColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'CHARGE\' in table \'v_courier\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tablev_courier.CHARGEColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public string OTHERCHARGE {
                get {
                    try {
                        return ((string)(this[this.tablev_courier.OTHERCHARGEColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'OTHERCHARGE\' in table \'v_courier\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tablev_courier.OTHERCHARGEColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public string DISKON {
                get {
                    try {
                        return ((string)(this[this.tablev_courier.DISKONColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'DISKON\' in table \'v_courier\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tablev_courier.DISKONColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public string TOTAL {
                get {
                    try {
                        return ((string)(this[this.tablev_courier.TOTALColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'TOTAL\' in table \'v_courier\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tablev_courier.TOTALColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public string STATUS {
                get {
                    try {
                        return ((string)(this[this.tablev_courier.STATUSColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'STATUS\' in table \'v_courier\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tablev_courier.STATUSColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public string NAMAPERUSAHAAN {
                get {
                    try {
                        return ((string)(this[this.tablev_courier.NAMAPERUSAHAANColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'NAMAPERUSAHAAN\' in table \'v_courier\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tablev_courier.NAMAPERUSAHAANColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public string ALAMATPERUSAHAAN {
                get {
                    try {
                        return ((string)(this[this.tablev_courier.ALAMATPERUSAHAANColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'ALAMATPERUSAHAAN\' in table \'v_courier\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tablev_courier.ALAMATPERUSAHAANColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public string TELPPERUSAHAAN {
                get {
                    try {
                        return ((string)(this[this.tablev_courier.TELPPERUSAHAANColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'TELPPERUSAHAAN\' in table \'v_courier\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tablev_courier.TELPPERUSAHAANColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public string FAXPERUSAHAAN {
                get {
                    try {
                        return ((string)(this[this.tablev_courier.FAXPERUSAHAANColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'FAXPERUSAHAAN\' in table \'v_courier\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tablev_courier.FAXPERUSAHAANColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IsNONull() {
                return this.IsNull(this.tablev_courier.NOColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetNONull() {
                this[this.tablev_courier.NOColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IsSTARTDATENull() {
                return this.IsNull(this.tablev_courier.STARTDATEColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetSTARTDATENull() {
                this[this.tablev_courier.STARTDATEColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IsENDDATENull() {
                return this.IsNull(this.tablev_courier.ENDDATEColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetENDDATENull() {
                this[this.tablev_courier.ENDDATEColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IsTGLTERIMANull() {
                return this.IsNull(this.tablev_courier.TGLTERIMAColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetTGLTERIMANull() {
                this[this.tablev_courier.TGLTERIMAColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IsCUSTOMERNull() {
                return this.IsNull(this.tablev_courier.CUSTOMERColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetCUSTOMERNull() {
                this[this.tablev_courier.CUSTOMERColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IsASALNull() {
                return this.IsNull(this.tablev_courier.ASALColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetASALNull() {
                this[this.tablev_courier.ASALColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IsTUJUANNull() {
                return this.IsNull(this.tablev_courier.TUJUANColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetTUJUANNull() {
                this[this.tablev_courier.TUJUANColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IsPENERIMANull() {
                return this.IsNull(this.tablev_courier.PENERIMAColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetPENERIMANull() {
                this[this.tablev_courier.PENERIMAColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IsSERVICENull() {
                return this.IsNull(this.tablev_courier.SERVICEColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetSERVICENull() {
                this[this.tablev_courier.SERVICEColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IsJENISKIRIMANNull() {
                return this.IsNull(this.tablev_courier.JENISKIRIMANColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetJENISKIRIMANNull() {
                this[this.tablev_courier.JENISKIRIMANColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IsJUMLAHNull() {
                return this.IsNull(this.tablev_courier.JUMLAHColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetJUMLAHNull() {
                this[this.tablev_courier.JUMLAHColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IsBERATNull() {
                return this.IsNull(this.tablev_courier.BERATColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetBERATNull() {
                this[this.tablev_courier.BERATColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IsCHARGENull() {
                return this.IsNull(this.tablev_courier.CHARGEColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetCHARGENull() {
                this[this.tablev_courier.CHARGEColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IsOTHERCHARGENull() {
                return this.IsNull(this.tablev_courier.OTHERCHARGEColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetOTHERCHARGENull() {
                this[this.tablev_courier.OTHERCHARGEColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IsDISKONNull() {
                return this.IsNull(this.tablev_courier.DISKONColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetDISKONNull() {
                this[this.tablev_courier.DISKONColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IsTOTALNull() {
                return this.IsNull(this.tablev_courier.TOTALColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetTOTALNull() {
                this[this.tablev_courier.TOTALColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IsSTATUSNull() {
                return this.IsNull(this.tablev_courier.STATUSColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetSTATUSNull() {
                this[this.tablev_courier.STATUSColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IsNAMAPERUSAHAANNull() {
                return this.IsNull(this.tablev_courier.NAMAPERUSAHAANColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetNAMAPERUSAHAANNull() {
                this[this.tablev_courier.NAMAPERUSAHAANColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IsALAMATPERUSAHAANNull() {
                return this.IsNull(this.tablev_courier.ALAMATPERUSAHAANColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetALAMATPERUSAHAANNull() {
                this[this.tablev_courier.ALAMATPERUSAHAANColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IsTELPPERUSAHAANNull() {
                return this.IsNull(this.tablev_courier.TELPPERUSAHAANColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetTELPPERUSAHAANNull() {
                this[this.tablev_courier.TELPPERUSAHAANColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IsFAXPERUSAHAANNull() {
                return this.IsNull(this.tablev_courier.FAXPERUSAHAANColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetFAXPERUSAHAANNull() {
                this[this.tablev_courier.FAXPERUSAHAANColumn] = global::System.Convert.DBNull;
            }
        }
        
        /// <summary>
        ///Row event argument class
        ///</summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "2.0.0.0")]
        public class v_courierRowChangeEvent : global::System.EventArgs {
            
            private v_courierRow eventRow;
            
            private global::System.Data.DataRowAction eventAction;
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public v_courierRowChangeEvent(v_courierRow row, global::System.Data.DataRowAction action) {
                this.eventRow = row;
                this.eventAction = action;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public v_courierRow Row {
                get {
                    return this.eventRow;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataRowAction Action {
                get {
                    return this.eventAction;
                }
            }
        }
    }
}

#pragma warning restore 1591