//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3053
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

#pragma warning disable 1591

namespace LOGISTICMANAGAMENTSYSTEM.REPORTS.EXPRESS {
    
    
    /// <summary>
    ///Represents a strongly typed in-memory cache of data.
    ///</summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "2.0.0.0")]
    [global::System.Serializable()]
    [global::System.ComponentModel.DesignerCategoryAttribute("code")]
    [global::System.ComponentModel.ToolboxItem(true)]
    [global::System.Xml.Serialization.XmlSchemaProviderAttribute("GetTypedDataSetSchema")]
    [global::System.Xml.Serialization.XmlRootAttribute("dsRESI")]
    [global::System.ComponentModel.Design.HelpKeywordAttribute("vs.data.DataSet")]
    public partial class dsRESI : global::System.Data.DataSet {
        
        private V_TRANSAKSIEXPRESSDataTable tableV_TRANSAKSIEXPRESS;
        
        private global::System.Data.SchemaSerializationMode _schemaSerializationMode = global::System.Data.SchemaSerializationMode.IncludeSchema;
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public dsRESI() {
            this.BeginInit();
            this.InitClass();
            global::System.ComponentModel.CollectionChangeEventHandler schemaChangedHandler = new global::System.ComponentModel.CollectionChangeEventHandler(this.SchemaChanged);
            base.Tables.CollectionChanged += schemaChangedHandler;
            base.Relations.CollectionChanged += schemaChangedHandler;
            this.EndInit();
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        protected dsRESI(global::System.Runtime.Serialization.SerializationInfo info, global::System.Runtime.Serialization.StreamingContext context) : 
                base(info, context, false) {
            if ((this.IsBinarySerialized(info, context) == true)) {
                this.InitVars(false);
                global::System.ComponentModel.CollectionChangeEventHandler schemaChangedHandler1 = new global::System.ComponentModel.CollectionChangeEventHandler(this.SchemaChanged);
                this.Tables.CollectionChanged += schemaChangedHandler1;
                this.Relations.CollectionChanged += schemaChangedHandler1;
                return;
            }
            string strSchema = ((string)(info.GetValue("XmlSchema", typeof(string))));
            if ((this.DetermineSchemaSerializationMode(info, context) == global::System.Data.SchemaSerializationMode.IncludeSchema)) {
                global::System.Data.DataSet ds = new global::System.Data.DataSet();
                ds.ReadXmlSchema(new global::System.Xml.XmlTextReader(new global::System.IO.StringReader(strSchema)));
                if ((ds.Tables["V_TRANSAKSIEXPRESS"] != null)) {
                    base.Tables.Add(new V_TRANSAKSIEXPRESSDataTable(ds.Tables["V_TRANSAKSIEXPRESS"]));
                }
                this.DataSetName = ds.DataSetName;
                this.Prefix = ds.Prefix;
                this.Namespace = ds.Namespace;
                this.Locale = ds.Locale;
                this.CaseSensitive = ds.CaseSensitive;
                this.EnforceConstraints = ds.EnforceConstraints;
                this.Merge(ds, false, global::System.Data.MissingSchemaAction.Add);
                this.InitVars();
            }
            else {
                this.ReadXmlSchema(new global::System.Xml.XmlTextReader(new global::System.IO.StringReader(strSchema)));
            }
            this.GetSerializationData(info, context);
            global::System.ComponentModel.CollectionChangeEventHandler schemaChangedHandler = new global::System.ComponentModel.CollectionChangeEventHandler(this.SchemaChanged);
            base.Tables.CollectionChanged += schemaChangedHandler;
            this.Relations.CollectionChanged += schemaChangedHandler;
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.ComponentModel.Browsable(false)]
        [global::System.ComponentModel.DesignerSerializationVisibility(global::System.ComponentModel.DesignerSerializationVisibility.Content)]
        public V_TRANSAKSIEXPRESSDataTable V_TRANSAKSIEXPRESS {
            get {
                return this.tableV_TRANSAKSIEXPRESS;
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.ComponentModel.BrowsableAttribute(true)]
        [global::System.ComponentModel.DesignerSerializationVisibilityAttribute(global::System.ComponentModel.DesignerSerializationVisibility.Visible)]
        public override global::System.Data.SchemaSerializationMode SchemaSerializationMode {
            get {
                return this._schemaSerializationMode;
            }
            set {
                this._schemaSerializationMode = value;
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.ComponentModel.DesignerSerializationVisibilityAttribute(global::System.ComponentModel.DesignerSerializationVisibility.Hidden)]
        public new global::System.Data.DataTableCollection Tables {
            get {
                return base.Tables;
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.ComponentModel.DesignerSerializationVisibilityAttribute(global::System.ComponentModel.DesignerSerializationVisibility.Hidden)]
        public new global::System.Data.DataRelationCollection Relations {
            get {
                return base.Relations;
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        protected override void InitializeDerivedDataSet() {
            this.BeginInit();
            this.InitClass();
            this.EndInit();
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public override global::System.Data.DataSet Clone() {
            dsRESI cln = ((dsRESI)(base.Clone()));
            cln.InitVars();
            cln.SchemaSerializationMode = this.SchemaSerializationMode;
            return cln;
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        protected override bool ShouldSerializeTables() {
            return false;
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        protected override bool ShouldSerializeRelations() {
            return false;
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        protected override void ReadXmlSerializable(global::System.Xml.XmlReader reader) {
            if ((this.DetermineSchemaSerializationMode(reader) == global::System.Data.SchemaSerializationMode.IncludeSchema)) {
                this.Reset();
                global::System.Data.DataSet ds = new global::System.Data.DataSet();
                ds.ReadXml(reader);
                if ((ds.Tables["V_TRANSAKSIEXPRESS"] != null)) {
                    base.Tables.Add(new V_TRANSAKSIEXPRESSDataTable(ds.Tables["V_TRANSAKSIEXPRESS"]));
                }
                this.DataSetName = ds.DataSetName;
                this.Prefix = ds.Prefix;
                this.Namespace = ds.Namespace;
                this.Locale = ds.Locale;
                this.CaseSensitive = ds.CaseSensitive;
                this.EnforceConstraints = ds.EnforceConstraints;
                this.Merge(ds, false, global::System.Data.MissingSchemaAction.Add);
                this.InitVars();
            }
            else {
                this.ReadXml(reader);
                this.InitVars();
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        protected override global::System.Xml.Schema.XmlSchema GetSchemaSerializable() {
            global::System.IO.MemoryStream stream = new global::System.IO.MemoryStream();
            this.WriteXmlSchema(new global::System.Xml.XmlTextWriter(stream, null));
            stream.Position = 0;
            return global::System.Xml.Schema.XmlSchema.Read(new global::System.Xml.XmlTextReader(stream), null);
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        internal void InitVars() {
            this.InitVars(true);
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        internal void InitVars(bool initTable) {
            this.tableV_TRANSAKSIEXPRESS = ((V_TRANSAKSIEXPRESSDataTable)(base.Tables["V_TRANSAKSIEXPRESS"]));
            if ((initTable == true)) {
                if ((this.tableV_TRANSAKSIEXPRESS != null)) {
                    this.tableV_TRANSAKSIEXPRESS.InitVars();
                }
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private void InitClass() {
            this.DataSetName = "dsRESI";
            this.Prefix = "";
            this.Namespace = "http://tempuri.org/dsRESI.xsd";
            this.EnforceConstraints = true;
            this.SchemaSerializationMode = global::System.Data.SchemaSerializationMode.IncludeSchema;
            this.tableV_TRANSAKSIEXPRESS = new V_TRANSAKSIEXPRESSDataTable();
            base.Tables.Add(this.tableV_TRANSAKSIEXPRESS);
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private bool ShouldSerializeV_TRANSAKSIEXPRESS() {
            return false;
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private void SchemaChanged(object sender, global::System.ComponentModel.CollectionChangeEventArgs e) {
            if ((e.Action == global::System.ComponentModel.CollectionChangeAction.Remove)) {
                this.InitVars();
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public static global::System.Xml.Schema.XmlSchemaComplexType GetTypedDataSetSchema(global::System.Xml.Schema.XmlSchemaSet xs) {
            dsRESI ds = new dsRESI();
            global::System.Xml.Schema.XmlSchemaComplexType type = new global::System.Xml.Schema.XmlSchemaComplexType();
            global::System.Xml.Schema.XmlSchemaSequence sequence = new global::System.Xml.Schema.XmlSchemaSequence();
            global::System.Xml.Schema.XmlSchemaAny any = new global::System.Xml.Schema.XmlSchemaAny();
            any.Namespace = ds.Namespace;
            sequence.Items.Add(any);
            type.Particle = sequence;
            global::System.Xml.Schema.XmlSchema dsSchema = ds.GetSchemaSerializable();
            if (xs.Contains(dsSchema.TargetNamespace)) {
                global::System.IO.MemoryStream s1 = new global::System.IO.MemoryStream();
                global::System.IO.MemoryStream s2 = new global::System.IO.MemoryStream();
                try {
                    global::System.Xml.Schema.XmlSchema schema = null;
                    dsSchema.Write(s1);
                    for (global::System.Collections.IEnumerator schemas = xs.Schemas(dsSchema.TargetNamespace).GetEnumerator(); schemas.MoveNext(); ) {
                        schema = ((global::System.Xml.Schema.XmlSchema)(schemas.Current));
                        s2.SetLength(0);
                        schema.Write(s2);
                        if ((s1.Length == s2.Length)) {
                            s1.Position = 0;
                            s2.Position = 0;
                            for (; ((s1.Position != s1.Length) 
                                        && (s1.ReadByte() == s2.ReadByte())); ) {
                                ;
                            }
                            if ((s1.Position == s1.Length)) {
                                return type;
                            }
                        }
                    }
                }
                finally {
                    if ((s1 != null)) {
                        s1.Close();
                    }
                    if ((s2 != null)) {
                        s2.Close();
                    }
                }
            }
            xs.Add(dsSchema);
            return type;
        }
        
        public delegate void V_TRANSAKSIEXPRESSRowChangeEventHandler(object sender, V_TRANSAKSIEXPRESSRowChangeEvent e);
        
        /// <summary>
        ///Represents the strongly named DataTable class.
        ///</summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "2.0.0.0")]
        [global::System.Serializable()]
        [global::System.Xml.Serialization.XmlSchemaProviderAttribute("GetTypedTableSchema")]
        public partial class V_TRANSAKSIEXPRESSDataTable : global::System.Data.TypedTableBase<V_TRANSAKSIEXPRESSRow> {
            
            private global::System.Data.DataColumn columnNORESI;
            
            private global::System.Data.DataColumn columnASAL;
            
            private global::System.Data.DataColumn columnTUJUAN;
            
            private global::System.Data.DataColumn columnBERAT;
            
            private global::System.Data.DataColumn columnJUMLAH;
            
            private global::System.Data.DataColumn columnPENGIRIM;
            
            private global::System.Data.DataColumn columnALAMATPENGIRIM;
            
            private global::System.Data.DataColumn columnPHONEPENGIRIM;
            
            private global::System.Data.DataColumn columnPENERIMA;
            
            private global::System.Data.DataColumn columnALAMATPENERIMA;
            
            private global::System.Data.DataColumn columnPHONEPENERIMA;
            
            private global::System.Data.DataColumn columnLAYANAN;
            
            private global::System.Data.DataColumn columnHARGA;
            
            private global::System.Data.DataColumn columnJENISKIRIMAN;
            
            private global::System.Data.DataColumn columnASURANSI;
            
            private global::System.Data.DataColumn columnPPN;
            
            private global::System.Data.DataColumn columnJUMLAHTOTAL;
            
            private global::System.Data.DataColumn columnKETERANGANISI;
            
            private global::System.Data.DataColumn columnINSTRUKSIKHUSUS;
            
            private global::System.Data.DataColumn columnDIM_P;
            
            private global::System.Data.DataColumn columnDIM_L;
            
            private global::System.Data.DataColumn columnDIM_T;
            
            private global::System.Data.DataColumn columnHPPENGIRIM;
            
            private global::System.Data.DataColumn columnPACKING;
            
            private global::System.Data.DataColumn columnBARCODE;
            
            private global::System.Data.DataColumn columnNAMAPERUSAHAAN;
            
            private global::System.Data.DataColumn columnALAMATPERUSAHAAN;
            
            private global::System.Data.DataColumn columnTELPPERUSAHAAN;
            
            private global::System.Data.DataColumn columnFAXPERUSAHAAN;
            
            private global::System.Data.DataColumn columnTGLMANIFEST;
            
            private global::System.Data.DataColumn columnETD;
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public V_TRANSAKSIEXPRESSDataTable() {
                this.TableName = "V_TRANSAKSIEXPRESS";
                this.BeginInit();
                this.InitClass();
                this.EndInit();
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            internal V_TRANSAKSIEXPRESSDataTable(global::System.Data.DataTable table) {
                this.TableName = table.TableName;
                if ((table.CaseSensitive != table.DataSet.CaseSensitive)) {
                    this.CaseSensitive = table.CaseSensitive;
                }
                if ((table.Locale.ToString() != table.DataSet.Locale.ToString())) {
                    this.Locale = table.Locale;
                }
                if ((table.Namespace != table.DataSet.Namespace)) {
                    this.Namespace = table.Namespace;
                }
                this.Prefix = table.Prefix;
                this.MinimumCapacity = table.MinimumCapacity;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            protected V_TRANSAKSIEXPRESSDataTable(global::System.Runtime.Serialization.SerializationInfo info, global::System.Runtime.Serialization.StreamingContext context) : 
                    base(info, context) {
                this.InitVars();
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn NORESIColumn {
                get {
                    return this.columnNORESI;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn ASALColumn {
                get {
                    return this.columnASAL;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn TUJUANColumn {
                get {
                    return this.columnTUJUAN;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn BERATColumn {
                get {
                    return this.columnBERAT;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn JUMLAHColumn {
                get {
                    return this.columnJUMLAH;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn PENGIRIMColumn {
                get {
                    return this.columnPENGIRIM;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn ALAMATPENGIRIMColumn {
                get {
                    return this.columnALAMATPENGIRIM;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn PHONEPENGIRIMColumn {
                get {
                    return this.columnPHONEPENGIRIM;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn PENERIMAColumn {
                get {
                    return this.columnPENERIMA;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn ALAMATPENERIMAColumn {
                get {
                    return this.columnALAMATPENERIMA;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn PHONEPENERIMAColumn {
                get {
                    return this.columnPHONEPENERIMA;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn LAYANANColumn {
                get {
                    return this.columnLAYANAN;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn HARGAColumn {
                get {
                    return this.columnHARGA;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn JENISKIRIMANColumn {
                get {
                    return this.columnJENISKIRIMAN;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn ASURANSIColumn {
                get {
                    return this.columnASURANSI;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn PPNColumn {
                get {
                    return this.columnPPN;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn JUMLAHTOTALColumn {
                get {
                    return this.columnJUMLAHTOTAL;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn KETERANGANISIColumn {
                get {
                    return this.columnKETERANGANISI;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn INSTRUKSIKHUSUSColumn {
                get {
                    return this.columnINSTRUKSIKHUSUS;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn DIM_PColumn {
                get {
                    return this.columnDIM_P;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn DIM_LColumn {
                get {
                    return this.columnDIM_L;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn DIM_TColumn {
                get {
                    return this.columnDIM_T;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn HPPENGIRIMColumn {
                get {
                    return this.columnHPPENGIRIM;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn PACKINGColumn {
                get {
                    return this.columnPACKING;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn BARCODEColumn {
                get {
                    return this.columnBARCODE;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn NAMAPERUSAHAANColumn {
                get {
                    return this.columnNAMAPERUSAHAAN;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn ALAMATPERUSAHAANColumn {
                get {
                    return this.columnALAMATPERUSAHAAN;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn TELPPERUSAHAANColumn {
                get {
                    return this.columnTELPPERUSAHAAN;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn FAXPERUSAHAANColumn {
                get {
                    return this.columnFAXPERUSAHAAN;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn TGLMANIFESTColumn {
                get {
                    return this.columnTGLMANIFEST;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn ETDColumn {
                get {
                    return this.columnETD;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.ComponentModel.Browsable(false)]
            public int Count {
                get {
                    return this.Rows.Count;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public V_TRANSAKSIEXPRESSRow this[int index] {
                get {
                    return ((V_TRANSAKSIEXPRESSRow)(this.Rows[index]));
                }
            }
            
            public event V_TRANSAKSIEXPRESSRowChangeEventHandler V_TRANSAKSIEXPRESSRowChanging;
            
            public event V_TRANSAKSIEXPRESSRowChangeEventHandler V_TRANSAKSIEXPRESSRowChanged;
            
            public event V_TRANSAKSIEXPRESSRowChangeEventHandler V_TRANSAKSIEXPRESSRowDeleting;
            
            public event V_TRANSAKSIEXPRESSRowChangeEventHandler V_TRANSAKSIEXPRESSRowDeleted;
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void AddV_TRANSAKSIEXPRESSRow(V_TRANSAKSIEXPRESSRow row) {
                this.Rows.Add(row);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public V_TRANSAKSIEXPRESSRow AddV_TRANSAKSIEXPRESSRow(
                        string NORESI, 
                        string ASAL, 
                        string TUJUAN, 
                        string BERAT, 
                        string JUMLAH, 
                        string PENGIRIM, 
                        string ALAMATPENGIRIM, 
                        string PHONEPENGIRIM, 
                        string PENERIMA, 
                        string ALAMATPENERIMA, 
                        string PHONEPENERIMA, 
                        string LAYANAN, 
                        string HARGA, 
                        string JENISKIRIMAN, 
                        string ASURANSI, 
                        string PPN, 
                        string JUMLAHTOTAL, 
                        string KETERANGANISI, 
                        string INSTRUKSIKHUSUS, 
                        string DIM_P, 
                        string DIM_L, 
                        string DIM_T, 
                        string HPPENGIRIM, 
                        string PACKING, 
                        sbyte BARCODE, 
                        string NAMAPERUSAHAAN, 
                        string ALAMATPERUSAHAAN, 
                        string TELPPERUSAHAAN, 
                        string FAXPERUSAHAAN, 
                        string TGLMANIFEST, 
                        string ETD) {
                V_TRANSAKSIEXPRESSRow rowV_TRANSAKSIEXPRESSRow = ((V_TRANSAKSIEXPRESSRow)(this.NewRow()));
                object[] columnValuesArray = new object[] {
                        NORESI,
                        ASAL,
                        TUJUAN,
                        BERAT,
                        JUMLAH,
                        PENGIRIM,
                        ALAMATPENGIRIM,
                        PHONEPENGIRIM,
                        PENERIMA,
                        ALAMATPENERIMA,
                        PHONEPENERIMA,
                        LAYANAN,
                        HARGA,
                        JENISKIRIMAN,
                        ASURANSI,
                        PPN,
                        JUMLAHTOTAL,
                        KETERANGANISI,
                        INSTRUKSIKHUSUS,
                        DIM_P,
                        DIM_L,
                        DIM_T,
                        HPPENGIRIM,
                        PACKING,
                        BARCODE,
                        NAMAPERUSAHAAN,
                        ALAMATPERUSAHAAN,
                        TELPPERUSAHAAN,
                        FAXPERUSAHAAN,
                        TGLMANIFEST,
                        ETD};
                rowV_TRANSAKSIEXPRESSRow.ItemArray = columnValuesArray;
                this.Rows.Add(rowV_TRANSAKSIEXPRESSRow);
                return rowV_TRANSAKSIEXPRESSRow;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public override global::System.Data.DataTable Clone() {
                V_TRANSAKSIEXPRESSDataTable cln = ((V_TRANSAKSIEXPRESSDataTable)(base.Clone()));
                cln.InitVars();
                return cln;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            protected override global::System.Data.DataTable CreateInstance() {
                return new V_TRANSAKSIEXPRESSDataTable();
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            internal void InitVars() {
                this.columnNORESI = base.Columns["NORESI"];
                this.columnASAL = base.Columns["ASAL"];
                this.columnTUJUAN = base.Columns["TUJUAN"];
                this.columnBERAT = base.Columns["BERAT"];
                this.columnJUMLAH = base.Columns["JUMLAH"];
                this.columnPENGIRIM = base.Columns["PENGIRIM"];
                this.columnALAMATPENGIRIM = base.Columns["ALAMATPENGIRIM"];
                this.columnPHONEPENGIRIM = base.Columns["PHONEPENGIRIM"];
                this.columnPENERIMA = base.Columns["PENERIMA"];
                this.columnALAMATPENERIMA = base.Columns["ALAMATPENERIMA"];
                this.columnPHONEPENERIMA = base.Columns["PHONEPENERIMA"];
                this.columnLAYANAN = base.Columns["LAYANAN"];
                this.columnHARGA = base.Columns["HARGA"];
                this.columnJENISKIRIMAN = base.Columns["JENISKIRIMAN"];
                this.columnASURANSI = base.Columns["ASURANSI"];
                this.columnPPN = base.Columns["PPN"];
                this.columnJUMLAHTOTAL = base.Columns["JUMLAHTOTAL"];
                this.columnKETERANGANISI = base.Columns["KETERANGANISI"];
                this.columnINSTRUKSIKHUSUS = base.Columns["INSTRUKSIKHUSUS"];
                this.columnDIM_P = base.Columns["DIM_P"];
                this.columnDIM_L = base.Columns["DIM_L"];
                this.columnDIM_T = base.Columns["DIM_T"];
                this.columnHPPENGIRIM = base.Columns["HPPENGIRIM"];
                this.columnPACKING = base.Columns["PACKING"];
                this.columnBARCODE = base.Columns["BARCODE"];
                this.columnNAMAPERUSAHAAN = base.Columns["NAMAPERUSAHAAN"];
                this.columnALAMATPERUSAHAAN = base.Columns["ALAMATPERUSAHAAN"];
                this.columnTELPPERUSAHAAN = base.Columns["TELPPERUSAHAAN"];
                this.columnFAXPERUSAHAAN = base.Columns["FAXPERUSAHAAN"];
                this.columnTGLMANIFEST = base.Columns["TGLMANIFEST"];
                this.columnETD = base.Columns["ETD"];
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            private void InitClass() {
                this.columnNORESI = new global::System.Data.DataColumn("NORESI", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnNORESI);
                this.columnASAL = new global::System.Data.DataColumn("ASAL", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnASAL);
                this.columnTUJUAN = new global::System.Data.DataColumn("TUJUAN", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnTUJUAN);
                this.columnBERAT = new global::System.Data.DataColumn("BERAT", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnBERAT);
                this.columnJUMLAH = new global::System.Data.DataColumn("JUMLAH", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnJUMLAH);
                this.columnPENGIRIM = new global::System.Data.DataColumn("PENGIRIM", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnPENGIRIM);
                this.columnALAMATPENGIRIM = new global::System.Data.DataColumn("ALAMATPENGIRIM", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnALAMATPENGIRIM);
                this.columnPHONEPENGIRIM = new global::System.Data.DataColumn("PHONEPENGIRIM", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnPHONEPENGIRIM);
                this.columnPENERIMA = new global::System.Data.DataColumn("PENERIMA", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnPENERIMA);
                this.columnALAMATPENERIMA = new global::System.Data.DataColumn("ALAMATPENERIMA", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnALAMATPENERIMA);
                this.columnPHONEPENERIMA = new global::System.Data.DataColumn("PHONEPENERIMA", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnPHONEPENERIMA);
                this.columnLAYANAN = new global::System.Data.DataColumn("LAYANAN", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnLAYANAN);
                this.columnHARGA = new global::System.Data.DataColumn("HARGA", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnHARGA);
                this.columnJENISKIRIMAN = new global::System.Data.DataColumn("JENISKIRIMAN", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnJENISKIRIMAN);
                this.columnASURANSI = new global::System.Data.DataColumn("ASURANSI", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnASURANSI);
                this.columnPPN = new global::System.Data.DataColumn("PPN", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnPPN);
                this.columnJUMLAHTOTAL = new global::System.Data.DataColumn("JUMLAHTOTAL", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnJUMLAHTOTAL);
                this.columnKETERANGANISI = new global::System.Data.DataColumn("KETERANGANISI", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnKETERANGANISI);
                this.columnINSTRUKSIKHUSUS = new global::System.Data.DataColumn("INSTRUKSIKHUSUS", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnINSTRUKSIKHUSUS);
                this.columnDIM_P = new global::System.Data.DataColumn("DIM_P", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnDIM_P);
                this.columnDIM_L = new global::System.Data.DataColumn("DIM_L", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnDIM_L);
                this.columnDIM_T = new global::System.Data.DataColumn("DIM_T", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnDIM_T);
                this.columnHPPENGIRIM = new global::System.Data.DataColumn("HPPENGIRIM", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnHPPENGIRIM);
                this.columnPACKING = new global::System.Data.DataColumn("PACKING", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnPACKING);
                this.columnBARCODE = new global::System.Data.DataColumn("BARCODE", typeof(sbyte), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnBARCODE);
                this.columnNAMAPERUSAHAAN = new global::System.Data.DataColumn("NAMAPERUSAHAAN", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnNAMAPERUSAHAAN);
                this.columnALAMATPERUSAHAAN = new global::System.Data.DataColumn("ALAMATPERUSAHAAN", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnALAMATPERUSAHAAN);
                this.columnTELPPERUSAHAAN = new global::System.Data.DataColumn("TELPPERUSAHAAN", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnTELPPERUSAHAAN);
                this.columnFAXPERUSAHAAN = new global::System.Data.DataColumn("FAXPERUSAHAAN", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnFAXPERUSAHAAN);
                this.columnTGLMANIFEST = new global::System.Data.DataColumn("TGLMANIFEST", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnTGLMANIFEST);
                this.columnETD = new global::System.Data.DataColumn("ETD", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnETD);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public V_TRANSAKSIEXPRESSRow NewV_TRANSAKSIEXPRESSRow() {
                return ((V_TRANSAKSIEXPRESSRow)(this.NewRow()));
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            protected override global::System.Data.DataRow NewRowFromBuilder(global::System.Data.DataRowBuilder builder) {
                return new V_TRANSAKSIEXPRESSRow(builder);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            protected override global::System.Type GetRowType() {
                return typeof(V_TRANSAKSIEXPRESSRow);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            protected override void OnRowChanged(global::System.Data.DataRowChangeEventArgs e) {
                base.OnRowChanged(e);
                if ((this.V_TRANSAKSIEXPRESSRowChanged != null)) {
                    this.V_TRANSAKSIEXPRESSRowChanged(this, new V_TRANSAKSIEXPRESSRowChangeEvent(((V_TRANSAKSIEXPRESSRow)(e.Row)), e.Action));
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            protected override void OnRowChanging(global::System.Data.DataRowChangeEventArgs e) {
                base.OnRowChanging(e);
                if ((this.V_TRANSAKSIEXPRESSRowChanging != null)) {
                    this.V_TRANSAKSIEXPRESSRowChanging(this, new V_TRANSAKSIEXPRESSRowChangeEvent(((V_TRANSAKSIEXPRESSRow)(e.Row)), e.Action));
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            protected override void OnRowDeleted(global::System.Data.DataRowChangeEventArgs e) {
                base.OnRowDeleted(e);
                if ((this.V_TRANSAKSIEXPRESSRowDeleted != null)) {
                    this.V_TRANSAKSIEXPRESSRowDeleted(this, new V_TRANSAKSIEXPRESSRowChangeEvent(((V_TRANSAKSIEXPRESSRow)(e.Row)), e.Action));
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            protected override void OnRowDeleting(global::System.Data.DataRowChangeEventArgs e) {
                base.OnRowDeleting(e);
                if ((this.V_TRANSAKSIEXPRESSRowDeleting != null)) {
                    this.V_TRANSAKSIEXPRESSRowDeleting(this, new V_TRANSAKSIEXPRESSRowChangeEvent(((V_TRANSAKSIEXPRESSRow)(e.Row)), e.Action));
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void RemoveV_TRANSAKSIEXPRESSRow(V_TRANSAKSIEXPRESSRow row) {
                this.Rows.Remove(row);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public static global::System.Xml.Schema.XmlSchemaComplexType GetTypedTableSchema(global::System.Xml.Schema.XmlSchemaSet xs) {
                global::System.Xml.Schema.XmlSchemaComplexType type = new global::System.Xml.Schema.XmlSchemaComplexType();
                global::System.Xml.Schema.XmlSchemaSequence sequence = new global::System.Xml.Schema.XmlSchemaSequence();
                dsRESI ds = new dsRESI();
                global::System.Xml.Schema.XmlSchemaAny any1 = new global::System.Xml.Schema.XmlSchemaAny();
                any1.Namespace = "http://www.w3.org/2001/XMLSchema";
                any1.MinOccurs = new decimal(0);
                any1.MaxOccurs = decimal.MaxValue;
                any1.ProcessContents = global::System.Xml.Schema.XmlSchemaContentProcessing.Lax;
                sequence.Items.Add(any1);
                global::System.Xml.Schema.XmlSchemaAny any2 = new global::System.Xml.Schema.XmlSchemaAny();
                any2.Namespace = "urn:schemas-microsoft-com:xml-diffgram-v1";
                any2.MinOccurs = new decimal(1);
                any2.ProcessContents = global::System.Xml.Schema.XmlSchemaContentProcessing.Lax;
                sequence.Items.Add(any2);
                global::System.Xml.Schema.XmlSchemaAttribute attribute1 = new global::System.Xml.Schema.XmlSchemaAttribute();
                attribute1.Name = "namespace";
                attribute1.FixedValue = ds.Namespace;
                type.Attributes.Add(attribute1);
                global::System.Xml.Schema.XmlSchemaAttribute attribute2 = new global::System.Xml.Schema.XmlSchemaAttribute();
                attribute2.Name = "tableTypeName";
                attribute2.FixedValue = "V_TRANSAKSIEXPRESSDataTable";
                type.Attributes.Add(attribute2);
                type.Particle = sequence;
                global::System.Xml.Schema.XmlSchema dsSchema = ds.GetSchemaSerializable();
                if (xs.Contains(dsSchema.TargetNamespace)) {
                    global::System.IO.MemoryStream s1 = new global::System.IO.MemoryStream();
                    global::System.IO.MemoryStream s2 = new global::System.IO.MemoryStream();
                    try {
                        global::System.Xml.Schema.XmlSchema schema = null;
                        dsSchema.Write(s1);
                        for (global::System.Collections.IEnumerator schemas = xs.Schemas(dsSchema.TargetNamespace).GetEnumerator(); schemas.MoveNext(); ) {
                            schema = ((global::System.Xml.Schema.XmlSchema)(schemas.Current));
                            s2.SetLength(0);
                            schema.Write(s2);
                            if ((s1.Length == s2.Length)) {
                                s1.Position = 0;
                                s2.Position = 0;
                                for (; ((s1.Position != s1.Length) 
                                            && (s1.ReadByte() == s2.ReadByte())); ) {
                                    ;
                                }
                                if ((s1.Position == s1.Length)) {
                                    return type;
                                }
                            }
                        }
                    }
                    finally {
                        if ((s1 != null)) {
                            s1.Close();
                        }
                        if ((s2 != null)) {
                            s2.Close();
                        }
                    }
                }
                xs.Add(dsSchema);
                return type;
            }
        }
        
        /// <summary>
        ///Represents strongly named DataRow class.
        ///</summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "2.0.0.0")]
        public partial class V_TRANSAKSIEXPRESSRow : global::System.Data.DataRow {
            
            private V_TRANSAKSIEXPRESSDataTable tableV_TRANSAKSIEXPRESS;
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            internal V_TRANSAKSIEXPRESSRow(global::System.Data.DataRowBuilder rb) : 
                    base(rb) {
                this.tableV_TRANSAKSIEXPRESS = ((V_TRANSAKSIEXPRESSDataTable)(this.Table));
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public string NORESI {
                get {
                    try {
                        return ((string)(this[this.tableV_TRANSAKSIEXPRESS.NORESIColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'NORESI\' in table \'V_TRANSAKSIEXPRESS\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tableV_TRANSAKSIEXPRESS.NORESIColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public string ASAL {
                get {
                    try {
                        return ((string)(this[this.tableV_TRANSAKSIEXPRESS.ASALColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'ASAL\' in table \'V_TRANSAKSIEXPRESS\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tableV_TRANSAKSIEXPRESS.ASALColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public string TUJUAN {
                get {
                    try {
                        return ((string)(this[this.tableV_TRANSAKSIEXPRESS.TUJUANColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'TUJUAN\' in table \'V_TRANSAKSIEXPRESS\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tableV_TRANSAKSIEXPRESS.TUJUANColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public string BERAT {
                get {
                    try {
                        return ((string)(this[this.tableV_TRANSAKSIEXPRESS.BERATColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'BERAT\' in table \'V_TRANSAKSIEXPRESS\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tableV_TRANSAKSIEXPRESS.BERATColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public string JUMLAH {
                get {
                    try {
                        return ((string)(this[this.tableV_TRANSAKSIEXPRESS.JUMLAHColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'JUMLAH\' in table \'V_TRANSAKSIEXPRESS\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tableV_TRANSAKSIEXPRESS.JUMLAHColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public string PENGIRIM {
                get {
                    try {
                        return ((string)(this[this.tableV_TRANSAKSIEXPRESS.PENGIRIMColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'PENGIRIM\' in table \'V_TRANSAKSIEXPRESS\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tableV_TRANSAKSIEXPRESS.PENGIRIMColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public string ALAMATPENGIRIM {
                get {
                    try {
                        return ((string)(this[this.tableV_TRANSAKSIEXPRESS.ALAMATPENGIRIMColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'ALAMATPENGIRIM\' in table \'V_TRANSAKSIEXPRESS\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tableV_TRANSAKSIEXPRESS.ALAMATPENGIRIMColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public string PHONEPENGIRIM {
                get {
                    try {
                        return ((string)(this[this.tableV_TRANSAKSIEXPRESS.PHONEPENGIRIMColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'PHONEPENGIRIM\' in table \'V_TRANSAKSIEXPRESS\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tableV_TRANSAKSIEXPRESS.PHONEPENGIRIMColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public string PENERIMA {
                get {
                    try {
                        return ((string)(this[this.tableV_TRANSAKSIEXPRESS.PENERIMAColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'PENERIMA\' in table \'V_TRANSAKSIEXPRESS\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tableV_TRANSAKSIEXPRESS.PENERIMAColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public string ALAMATPENERIMA {
                get {
                    try {
                        return ((string)(this[this.tableV_TRANSAKSIEXPRESS.ALAMATPENERIMAColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'ALAMATPENERIMA\' in table \'V_TRANSAKSIEXPRESS\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tableV_TRANSAKSIEXPRESS.ALAMATPENERIMAColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public string PHONEPENERIMA {
                get {
                    try {
                        return ((string)(this[this.tableV_TRANSAKSIEXPRESS.PHONEPENERIMAColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'PHONEPENERIMA\' in table \'V_TRANSAKSIEXPRESS\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tableV_TRANSAKSIEXPRESS.PHONEPENERIMAColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public string LAYANAN {
                get {
                    try {
                        return ((string)(this[this.tableV_TRANSAKSIEXPRESS.LAYANANColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'LAYANAN\' in table \'V_TRANSAKSIEXPRESS\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tableV_TRANSAKSIEXPRESS.LAYANANColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public string HARGA {
                get {
                    try {
                        return ((string)(this[this.tableV_TRANSAKSIEXPRESS.HARGAColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'HARGA\' in table \'V_TRANSAKSIEXPRESS\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tableV_TRANSAKSIEXPRESS.HARGAColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public string JENISKIRIMAN {
                get {
                    try {
                        return ((string)(this[this.tableV_TRANSAKSIEXPRESS.JENISKIRIMANColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'JENISKIRIMAN\' in table \'V_TRANSAKSIEXPRESS\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tableV_TRANSAKSIEXPRESS.JENISKIRIMANColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public string ASURANSI {
                get {
                    try {
                        return ((string)(this[this.tableV_TRANSAKSIEXPRESS.ASURANSIColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'ASURANSI\' in table \'V_TRANSAKSIEXPRESS\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tableV_TRANSAKSIEXPRESS.ASURANSIColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public string PPN {
                get {
                    try {
                        return ((string)(this[this.tableV_TRANSAKSIEXPRESS.PPNColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'PPN\' in table \'V_TRANSAKSIEXPRESS\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tableV_TRANSAKSIEXPRESS.PPNColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public string JUMLAHTOTAL {
                get {
                    try {
                        return ((string)(this[this.tableV_TRANSAKSIEXPRESS.JUMLAHTOTALColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'JUMLAHTOTAL\' in table \'V_TRANSAKSIEXPRESS\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tableV_TRANSAKSIEXPRESS.JUMLAHTOTALColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public string KETERANGANISI {
                get {
                    try {
                        return ((string)(this[this.tableV_TRANSAKSIEXPRESS.KETERANGANISIColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'KETERANGANISI\' in table \'V_TRANSAKSIEXPRESS\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tableV_TRANSAKSIEXPRESS.KETERANGANISIColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public string INSTRUKSIKHUSUS {
                get {
                    try {
                        return ((string)(this[this.tableV_TRANSAKSIEXPRESS.INSTRUKSIKHUSUSColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'INSTRUKSIKHUSUS\' in table \'V_TRANSAKSIEXPRESS\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tableV_TRANSAKSIEXPRESS.INSTRUKSIKHUSUSColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public string DIM_P {
                get {
                    try {
                        return ((string)(this[this.tableV_TRANSAKSIEXPRESS.DIM_PColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'DIM_P\' in table \'V_TRANSAKSIEXPRESS\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tableV_TRANSAKSIEXPRESS.DIM_PColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public string DIM_L {
                get {
                    try {
                        return ((string)(this[this.tableV_TRANSAKSIEXPRESS.DIM_LColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'DIM_L\' in table \'V_TRANSAKSIEXPRESS\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tableV_TRANSAKSIEXPRESS.DIM_LColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public string DIM_T {
                get {
                    try {
                        return ((string)(this[this.tableV_TRANSAKSIEXPRESS.DIM_TColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'DIM_T\' in table \'V_TRANSAKSIEXPRESS\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tableV_TRANSAKSIEXPRESS.DIM_TColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public string HPPENGIRIM {
                get {
                    try {
                        return ((string)(this[this.tableV_TRANSAKSIEXPRESS.HPPENGIRIMColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'HPPENGIRIM\' in table \'V_TRANSAKSIEXPRESS\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tableV_TRANSAKSIEXPRESS.HPPENGIRIMColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public string PACKING {
                get {
                    try {
                        return ((string)(this[this.tableV_TRANSAKSIEXPRESS.PACKINGColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'PACKING\' in table \'V_TRANSAKSIEXPRESS\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tableV_TRANSAKSIEXPRESS.PACKINGColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public sbyte BARCODE {
                get {
                    try {
                        return ((sbyte)(this[this.tableV_TRANSAKSIEXPRESS.BARCODEColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'BARCODE\' in table \'V_TRANSAKSIEXPRESS\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tableV_TRANSAKSIEXPRESS.BARCODEColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public string NAMAPERUSAHAAN {
                get {
                    try {
                        return ((string)(this[this.tableV_TRANSAKSIEXPRESS.NAMAPERUSAHAANColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'NAMAPERUSAHAAN\' in table \'V_TRANSAKSIEXPRESS\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tableV_TRANSAKSIEXPRESS.NAMAPERUSAHAANColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public string ALAMATPERUSAHAAN {
                get {
                    try {
                        return ((string)(this[this.tableV_TRANSAKSIEXPRESS.ALAMATPERUSAHAANColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'ALAMATPERUSAHAAN\' in table \'V_TRANSAKSIEXPRESS\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tableV_TRANSAKSIEXPRESS.ALAMATPERUSAHAANColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public string TELPPERUSAHAAN {
                get {
                    try {
                        return ((string)(this[this.tableV_TRANSAKSIEXPRESS.TELPPERUSAHAANColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'TELPPERUSAHAAN\' in table \'V_TRANSAKSIEXPRESS\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tableV_TRANSAKSIEXPRESS.TELPPERUSAHAANColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public string FAXPERUSAHAAN {
                get {
                    try {
                        return ((string)(this[this.tableV_TRANSAKSIEXPRESS.FAXPERUSAHAANColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'FAXPERUSAHAAN\' in table \'V_TRANSAKSIEXPRESS\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tableV_TRANSAKSIEXPRESS.FAXPERUSAHAANColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public string TGLMANIFEST {
                get {
                    try {
                        return ((string)(this[this.tableV_TRANSAKSIEXPRESS.TGLMANIFESTColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'TGLMANIFEST\' in table \'V_TRANSAKSIEXPRESS\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tableV_TRANSAKSIEXPRESS.TGLMANIFESTColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public string ETD {
                get {
                    try {
                        return ((string)(this[this.tableV_TRANSAKSIEXPRESS.ETDColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'ETD\' in table \'V_TRANSAKSIEXPRESS\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tableV_TRANSAKSIEXPRESS.ETDColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IsNORESINull() {
                return this.IsNull(this.tableV_TRANSAKSIEXPRESS.NORESIColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetNORESINull() {
                this[this.tableV_TRANSAKSIEXPRESS.NORESIColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IsASALNull() {
                return this.IsNull(this.tableV_TRANSAKSIEXPRESS.ASALColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetASALNull() {
                this[this.tableV_TRANSAKSIEXPRESS.ASALColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IsTUJUANNull() {
                return this.IsNull(this.tableV_TRANSAKSIEXPRESS.TUJUANColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetTUJUANNull() {
                this[this.tableV_TRANSAKSIEXPRESS.TUJUANColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IsBERATNull() {
                return this.IsNull(this.tableV_TRANSAKSIEXPRESS.BERATColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetBERATNull() {
                this[this.tableV_TRANSAKSIEXPRESS.BERATColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IsJUMLAHNull() {
                return this.IsNull(this.tableV_TRANSAKSIEXPRESS.JUMLAHColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetJUMLAHNull() {
                this[this.tableV_TRANSAKSIEXPRESS.JUMLAHColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IsPENGIRIMNull() {
                return this.IsNull(this.tableV_TRANSAKSIEXPRESS.PENGIRIMColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetPENGIRIMNull() {
                this[this.tableV_TRANSAKSIEXPRESS.PENGIRIMColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IsALAMATPENGIRIMNull() {
                return this.IsNull(this.tableV_TRANSAKSIEXPRESS.ALAMATPENGIRIMColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetALAMATPENGIRIMNull() {
                this[this.tableV_TRANSAKSIEXPRESS.ALAMATPENGIRIMColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IsPHONEPENGIRIMNull() {
                return this.IsNull(this.tableV_TRANSAKSIEXPRESS.PHONEPENGIRIMColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetPHONEPENGIRIMNull() {
                this[this.tableV_TRANSAKSIEXPRESS.PHONEPENGIRIMColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IsPENERIMANull() {
                return this.IsNull(this.tableV_TRANSAKSIEXPRESS.PENERIMAColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetPENERIMANull() {
                this[this.tableV_TRANSAKSIEXPRESS.PENERIMAColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IsALAMATPENERIMANull() {
                return this.IsNull(this.tableV_TRANSAKSIEXPRESS.ALAMATPENERIMAColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetALAMATPENERIMANull() {
                this[this.tableV_TRANSAKSIEXPRESS.ALAMATPENERIMAColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IsPHONEPENERIMANull() {
                return this.IsNull(this.tableV_TRANSAKSIEXPRESS.PHONEPENERIMAColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetPHONEPENERIMANull() {
                this[this.tableV_TRANSAKSIEXPRESS.PHONEPENERIMAColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IsLAYANANNull() {
                return this.IsNull(this.tableV_TRANSAKSIEXPRESS.LAYANANColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetLAYANANNull() {
                this[this.tableV_TRANSAKSIEXPRESS.LAYANANColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IsHARGANull() {
                return this.IsNull(this.tableV_TRANSAKSIEXPRESS.HARGAColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetHARGANull() {
                this[this.tableV_TRANSAKSIEXPRESS.HARGAColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IsJENISKIRIMANNull() {
                return this.IsNull(this.tableV_TRANSAKSIEXPRESS.JENISKIRIMANColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetJENISKIRIMANNull() {
                this[this.tableV_TRANSAKSIEXPRESS.JENISKIRIMANColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IsASURANSINull() {
                return this.IsNull(this.tableV_TRANSAKSIEXPRESS.ASURANSIColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetASURANSINull() {
                this[this.tableV_TRANSAKSIEXPRESS.ASURANSIColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IsPPNNull() {
                return this.IsNull(this.tableV_TRANSAKSIEXPRESS.PPNColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetPPNNull() {
                this[this.tableV_TRANSAKSIEXPRESS.PPNColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IsJUMLAHTOTALNull() {
                return this.IsNull(this.tableV_TRANSAKSIEXPRESS.JUMLAHTOTALColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetJUMLAHTOTALNull() {
                this[this.tableV_TRANSAKSIEXPRESS.JUMLAHTOTALColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IsKETERANGANISINull() {
                return this.IsNull(this.tableV_TRANSAKSIEXPRESS.KETERANGANISIColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetKETERANGANISINull() {
                this[this.tableV_TRANSAKSIEXPRESS.KETERANGANISIColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IsINSTRUKSIKHUSUSNull() {
                return this.IsNull(this.tableV_TRANSAKSIEXPRESS.INSTRUKSIKHUSUSColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetINSTRUKSIKHUSUSNull() {
                this[this.tableV_TRANSAKSIEXPRESS.INSTRUKSIKHUSUSColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IsDIM_PNull() {
                return this.IsNull(this.tableV_TRANSAKSIEXPRESS.DIM_PColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetDIM_PNull() {
                this[this.tableV_TRANSAKSIEXPRESS.DIM_PColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IsDIM_LNull() {
                return this.IsNull(this.tableV_TRANSAKSIEXPRESS.DIM_LColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetDIM_LNull() {
                this[this.tableV_TRANSAKSIEXPRESS.DIM_LColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IsDIM_TNull() {
                return this.IsNull(this.tableV_TRANSAKSIEXPRESS.DIM_TColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetDIM_TNull() {
                this[this.tableV_TRANSAKSIEXPRESS.DIM_TColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IsHPPENGIRIMNull() {
                return this.IsNull(this.tableV_TRANSAKSIEXPRESS.HPPENGIRIMColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetHPPENGIRIMNull() {
                this[this.tableV_TRANSAKSIEXPRESS.HPPENGIRIMColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IsPACKINGNull() {
                return this.IsNull(this.tableV_TRANSAKSIEXPRESS.PACKINGColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetPACKINGNull() {
                this[this.tableV_TRANSAKSIEXPRESS.PACKINGColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IsBARCODENull() {
                return this.IsNull(this.tableV_TRANSAKSIEXPRESS.BARCODEColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetBARCODENull() {
                this[this.tableV_TRANSAKSIEXPRESS.BARCODEColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IsNAMAPERUSAHAANNull() {
                return this.IsNull(this.tableV_TRANSAKSIEXPRESS.NAMAPERUSAHAANColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetNAMAPERUSAHAANNull() {
                this[this.tableV_TRANSAKSIEXPRESS.NAMAPERUSAHAANColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IsALAMATPERUSAHAANNull() {
                return this.IsNull(this.tableV_TRANSAKSIEXPRESS.ALAMATPERUSAHAANColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetALAMATPERUSAHAANNull() {
                this[this.tableV_TRANSAKSIEXPRESS.ALAMATPERUSAHAANColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IsTELPPERUSAHAANNull() {
                return this.IsNull(this.tableV_TRANSAKSIEXPRESS.TELPPERUSAHAANColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetTELPPERUSAHAANNull() {
                this[this.tableV_TRANSAKSIEXPRESS.TELPPERUSAHAANColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IsFAXPERUSAHAANNull() {
                return this.IsNull(this.tableV_TRANSAKSIEXPRESS.FAXPERUSAHAANColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetFAXPERUSAHAANNull() {
                this[this.tableV_TRANSAKSIEXPRESS.FAXPERUSAHAANColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IsTGLMANIFESTNull() {
                return this.IsNull(this.tableV_TRANSAKSIEXPRESS.TGLMANIFESTColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetTGLMANIFESTNull() {
                this[this.tableV_TRANSAKSIEXPRESS.TGLMANIFESTColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IsETDNull() {
                return this.IsNull(this.tableV_TRANSAKSIEXPRESS.ETDColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetETDNull() {
                this[this.tableV_TRANSAKSIEXPRESS.ETDColumn] = global::System.Convert.DBNull;
            }
        }
        
        /// <summary>
        ///Row event argument class
        ///</summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "2.0.0.0")]
        public class V_TRANSAKSIEXPRESSRowChangeEvent : global::System.EventArgs {
            
            private V_TRANSAKSIEXPRESSRow eventRow;
            
            private global::System.Data.DataRowAction eventAction;
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public V_TRANSAKSIEXPRESSRowChangeEvent(V_TRANSAKSIEXPRESSRow row, global::System.Data.DataRowAction action) {
                this.eventRow = row;
                this.eventAction = action;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public V_TRANSAKSIEXPRESSRow Row {
                get {
                    return this.eventRow;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataRowAction Action {
                get {
                    return this.eventAction;
                }
            }
        }
    }
}

#pragma warning restore 1591