//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3053
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

#pragma warning disable 1591

namespace LOGISTICMANAGAMENTSYSTEM.REPORTS.INVOICE {
    
    
    /// <summary>
    ///Represents a strongly typed in-memory cache of data.
    ///</summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "2.0.0.0")]
    [global::System.Serializable()]
    [global::System.ComponentModel.DesignerCategoryAttribute("code")]
    [global::System.ComponentModel.ToolboxItem(true)]
    [global::System.Xml.Serialization.XmlSchemaProviderAttribute("GetTypedDataSetSchema")]
    [global::System.Xml.Serialization.XmlRootAttribute("dsBIAYA")]
    [global::System.ComponentModel.Design.HelpKeywordAttribute("vs.data.DataSet")]
    public partial class dsBIAYA : global::System.Data.DataSet {
        
        private V_BIAYASTTDataTable tableV_BIAYASTT;
        
        private global::System.Data.SchemaSerializationMode _schemaSerializationMode = global::System.Data.SchemaSerializationMode.IncludeSchema;
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public dsBIAYA() {
            this.BeginInit();
            this.InitClass();
            global::System.ComponentModel.CollectionChangeEventHandler schemaChangedHandler = new global::System.ComponentModel.CollectionChangeEventHandler(this.SchemaChanged);
            base.Tables.CollectionChanged += schemaChangedHandler;
            base.Relations.CollectionChanged += schemaChangedHandler;
            this.EndInit();
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        protected dsBIAYA(global::System.Runtime.Serialization.SerializationInfo info, global::System.Runtime.Serialization.StreamingContext context) : 
                base(info, context, false) {
            if ((this.IsBinarySerialized(info, context) == true)) {
                this.InitVars(false);
                global::System.ComponentModel.CollectionChangeEventHandler schemaChangedHandler1 = new global::System.ComponentModel.CollectionChangeEventHandler(this.SchemaChanged);
                this.Tables.CollectionChanged += schemaChangedHandler1;
                this.Relations.CollectionChanged += schemaChangedHandler1;
                return;
            }
            string strSchema = ((string)(info.GetValue("XmlSchema", typeof(string))));
            if ((this.DetermineSchemaSerializationMode(info, context) == global::System.Data.SchemaSerializationMode.IncludeSchema)) {
                global::System.Data.DataSet ds = new global::System.Data.DataSet();
                ds.ReadXmlSchema(new global::System.Xml.XmlTextReader(new global::System.IO.StringReader(strSchema)));
                if ((ds.Tables["V_BIAYASTT"] != null)) {
                    base.Tables.Add(new V_BIAYASTTDataTable(ds.Tables["V_BIAYASTT"]));
                }
                this.DataSetName = ds.DataSetName;
                this.Prefix = ds.Prefix;
                this.Namespace = ds.Namespace;
                this.Locale = ds.Locale;
                this.CaseSensitive = ds.CaseSensitive;
                this.EnforceConstraints = ds.EnforceConstraints;
                this.Merge(ds, false, global::System.Data.MissingSchemaAction.Add);
                this.InitVars();
            }
            else {
                this.ReadXmlSchema(new global::System.Xml.XmlTextReader(new global::System.IO.StringReader(strSchema)));
            }
            this.GetSerializationData(info, context);
            global::System.ComponentModel.CollectionChangeEventHandler schemaChangedHandler = new global::System.ComponentModel.CollectionChangeEventHandler(this.SchemaChanged);
            base.Tables.CollectionChanged += schemaChangedHandler;
            this.Relations.CollectionChanged += schemaChangedHandler;
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.ComponentModel.Browsable(false)]
        [global::System.ComponentModel.DesignerSerializationVisibility(global::System.ComponentModel.DesignerSerializationVisibility.Content)]
        public V_BIAYASTTDataTable V_BIAYASTT {
            get {
                return this.tableV_BIAYASTT;
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.ComponentModel.BrowsableAttribute(true)]
        [global::System.ComponentModel.DesignerSerializationVisibilityAttribute(global::System.ComponentModel.DesignerSerializationVisibility.Visible)]
        public override global::System.Data.SchemaSerializationMode SchemaSerializationMode {
            get {
                return this._schemaSerializationMode;
            }
            set {
                this._schemaSerializationMode = value;
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.ComponentModel.DesignerSerializationVisibilityAttribute(global::System.ComponentModel.DesignerSerializationVisibility.Hidden)]
        public new global::System.Data.DataTableCollection Tables {
            get {
                return base.Tables;
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.ComponentModel.DesignerSerializationVisibilityAttribute(global::System.ComponentModel.DesignerSerializationVisibility.Hidden)]
        public new global::System.Data.DataRelationCollection Relations {
            get {
                return base.Relations;
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        protected override void InitializeDerivedDataSet() {
            this.BeginInit();
            this.InitClass();
            this.EndInit();
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public override global::System.Data.DataSet Clone() {
            dsBIAYA cln = ((dsBIAYA)(base.Clone()));
            cln.InitVars();
            cln.SchemaSerializationMode = this.SchemaSerializationMode;
            return cln;
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        protected override bool ShouldSerializeTables() {
            return false;
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        protected override bool ShouldSerializeRelations() {
            return false;
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        protected override void ReadXmlSerializable(global::System.Xml.XmlReader reader) {
            if ((this.DetermineSchemaSerializationMode(reader) == global::System.Data.SchemaSerializationMode.IncludeSchema)) {
                this.Reset();
                global::System.Data.DataSet ds = new global::System.Data.DataSet();
                ds.ReadXml(reader);
                if ((ds.Tables["V_BIAYASTT"] != null)) {
                    base.Tables.Add(new V_BIAYASTTDataTable(ds.Tables["V_BIAYASTT"]));
                }
                this.DataSetName = ds.DataSetName;
                this.Prefix = ds.Prefix;
                this.Namespace = ds.Namespace;
                this.Locale = ds.Locale;
                this.CaseSensitive = ds.CaseSensitive;
                this.EnforceConstraints = ds.EnforceConstraints;
                this.Merge(ds, false, global::System.Data.MissingSchemaAction.Add);
                this.InitVars();
            }
            else {
                this.ReadXml(reader);
                this.InitVars();
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        protected override global::System.Xml.Schema.XmlSchema GetSchemaSerializable() {
            global::System.IO.MemoryStream stream = new global::System.IO.MemoryStream();
            this.WriteXmlSchema(new global::System.Xml.XmlTextWriter(stream, null));
            stream.Position = 0;
            return global::System.Xml.Schema.XmlSchema.Read(new global::System.Xml.XmlTextReader(stream), null);
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        internal void InitVars() {
            this.InitVars(true);
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        internal void InitVars(bool initTable) {
            this.tableV_BIAYASTT = ((V_BIAYASTTDataTable)(base.Tables["V_BIAYASTT"]));
            if ((initTable == true)) {
                if ((this.tableV_BIAYASTT != null)) {
                    this.tableV_BIAYASTT.InitVars();
                }
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private void InitClass() {
            this.DataSetName = "dsBIAYA";
            this.Prefix = "";
            this.Namespace = "http://tempuri.org/dsBIAYA.xsd";
            this.EnforceConstraints = true;
            this.SchemaSerializationMode = global::System.Data.SchemaSerializationMode.IncludeSchema;
            this.tableV_BIAYASTT = new V_BIAYASTTDataTable();
            base.Tables.Add(this.tableV_BIAYASTT);
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private bool ShouldSerializeV_BIAYASTT() {
            return false;
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private void SchemaChanged(object sender, global::System.ComponentModel.CollectionChangeEventArgs e) {
            if ((e.Action == global::System.ComponentModel.CollectionChangeAction.Remove)) {
                this.InitVars();
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public static global::System.Xml.Schema.XmlSchemaComplexType GetTypedDataSetSchema(global::System.Xml.Schema.XmlSchemaSet xs) {
            dsBIAYA ds = new dsBIAYA();
            global::System.Xml.Schema.XmlSchemaComplexType type = new global::System.Xml.Schema.XmlSchemaComplexType();
            global::System.Xml.Schema.XmlSchemaSequence sequence = new global::System.Xml.Schema.XmlSchemaSequence();
            global::System.Xml.Schema.XmlSchemaAny any = new global::System.Xml.Schema.XmlSchemaAny();
            any.Namespace = ds.Namespace;
            sequence.Items.Add(any);
            type.Particle = sequence;
            global::System.Xml.Schema.XmlSchema dsSchema = ds.GetSchemaSerializable();
            if (xs.Contains(dsSchema.TargetNamespace)) {
                global::System.IO.MemoryStream s1 = new global::System.IO.MemoryStream();
                global::System.IO.MemoryStream s2 = new global::System.IO.MemoryStream();
                try {
                    global::System.Xml.Schema.XmlSchema schema = null;
                    dsSchema.Write(s1);
                    for (global::System.Collections.IEnumerator schemas = xs.Schemas(dsSchema.TargetNamespace).GetEnumerator(); schemas.MoveNext(); ) {
                        schema = ((global::System.Xml.Schema.XmlSchema)(schemas.Current));
                        s2.SetLength(0);
                        schema.Write(s2);
                        if ((s1.Length == s2.Length)) {
                            s1.Position = 0;
                            s2.Position = 0;
                            for (; ((s1.Position != s1.Length) 
                                        && (s1.ReadByte() == s2.ReadByte())); ) {
                                ;
                            }
                            if ((s1.Position == s1.Length)) {
                                return type;
                            }
                        }
                    }
                }
                finally {
                    if ((s1 != null)) {
                        s1.Close();
                    }
                    if ((s2 != null)) {
                        s2.Close();
                    }
                }
            }
            xs.Add(dsSchema);
            return type;
        }
        
        public delegate void V_BIAYASTTRowChangeEventHandler(object sender, V_BIAYASTTRowChangeEvent e);
        
        /// <summary>
        ///Represents the strongly named DataTable class.
        ///</summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "2.0.0.0")]
        [global::System.Serializable()]
        [global::System.Xml.Serialization.XmlSchemaProviderAttribute("GetTypedTableSchema")]
        public partial class V_BIAYASTTDataTable : global::System.Data.TypedTableBase<V_BIAYASTTRow> {
            
            private global::System.Data.DataColumn columnSTARTDATE;
            
            private global::System.Data.DataColumn columnENDDATE;
            
            private global::System.Data.DataColumn columnDATE;
            
            private global::System.Data.DataColumn columnCUSTOMER;
            
            private global::System.Data.DataColumn columnSTT;
            
            private global::System.Data.DataColumn columnDEST;
            
            private global::System.Data.DataColumn columnARMADA;
            
            private global::System.Data.DataColumn columnSERVICE;
            
            private global::System.Data.DataColumn columnBERAT;
            
            private global::System.Data.DataColumn columnTOTAL;
            
            private global::System.Data.DataColumn columnFEEMKRT;
            
            private global::System.Data.DataColumn columnRC;
            
            private global::System.Data.DataColumn columnCOSTSMU;
            
            private global::System.Data.DataColumn columnCOSTGRDH;
            
            private global::System.Data.DataColumn columnCOSTWH;
            
            private global::System.Data.DataColumn columnCOSTDARAT;
            
            private global::System.Data.DataColumn columnCOSTLAUT;
            
            private global::System.Data.DataColumn columnCOSTDELIVERY;
            
            private global::System.Data.DataColumn columnCOSTRA;
            
            private global::System.Data.DataColumn columnTOTALCOST;
            
            private global::System.Data.DataColumn columnPROFIT;
            
            private global::System.Data.DataColumn columnPROFITPERCENT;
            
            private global::System.Data.DataColumn columnOPT1;
            
            private global::System.Data.DataColumn columnOPT2;
            
            private global::System.Data.DataColumn columnOPT3;
            
            private global::System.Data.DataColumn columnNAMAPERUSAHAAN;
            
            private global::System.Data.DataColumn columnALAMATPERUSAHAAN;
            
            private global::System.Data.DataColumn columnTELPPERUSAHAAN;
            
            private global::System.Data.DataColumn columnFAXPERUSAHAAN;
            
            private global::System.Data.DataColumn columnNO;
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public V_BIAYASTTDataTable() {
                this.TableName = "V_BIAYASTT";
                this.BeginInit();
                this.InitClass();
                this.EndInit();
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            internal V_BIAYASTTDataTable(global::System.Data.DataTable table) {
                this.TableName = table.TableName;
                if ((table.CaseSensitive != table.DataSet.CaseSensitive)) {
                    this.CaseSensitive = table.CaseSensitive;
                }
                if ((table.Locale.ToString() != table.DataSet.Locale.ToString())) {
                    this.Locale = table.Locale;
                }
                if ((table.Namespace != table.DataSet.Namespace)) {
                    this.Namespace = table.Namespace;
                }
                this.Prefix = table.Prefix;
                this.MinimumCapacity = table.MinimumCapacity;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            protected V_BIAYASTTDataTable(global::System.Runtime.Serialization.SerializationInfo info, global::System.Runtime.Serialization.StreamingContext context) : 
                    base(info, context) {
                this.InitVars();
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn STARTDATEColumn {
                get {
                    return this.columnSTARTDATE;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn ENDDATEColumn {
                get {
                    return this.columnENDDATE;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn DATEColumn {
                get {
                    return this.columnDATE;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn CUSTOMERColumn {
                get {
                    return this.columnCUSTOMER;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn STTColumn {
                get {
                    return this.columnSTT;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn DESTColumn {
                get {
                    return this.columnDEST;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn ARMADAColumn {
                get {
                    return this.columnARMADA;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn SERVICEColumn {
                get {
                    return this.columnSERVICE;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn BERATColumn {
                get {
                    return this.columnBERAT;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn TOTALColumn {
                get {
                    return this.columnTOTAL;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn FEEMKRTColumn {
                get {
                    return this.columnFEEMKRT;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn RCColumn {
                get {
                    return this.columnRC;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn COSTSMUColumn {
                get {
                    return this.columnCOSTSMU;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn COSTGRDHColumn {
                get {
                    return this.columnCOSTGRDH;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn COSTWHColumn {
                get {
                    return this.columnCOSTWH;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn COSTDARATColumn {
                get {
                    return this.columnCOSTDARAT;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn COSTLAUTColumn {
                get {
                    return this.columnCOSTLAUT;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn COSTDELIVERYColumn {
                get {
                    return this.columnCOSTDELIVERY;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn COSTRAColumn {
                get {
                    return this.columnCOSTRA;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn TOTALCOSTColumn {
                get {
                    return this.columnTOTALCOST;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn PROFITColumn {
                get {
                    return this.columnPROFIT;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn PROFITPERCENTColumn {
                get {
                    return this.columnPROFITPERCENT;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn OPT1Column {
                get {
                    return this.columnOPT1;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn OPT2Column {
                get {
                    return this.columnOPT2;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn OPT3Column {
                get {
                    return this.columnOPT3;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn NAMAPERUSAHAANColumn {
                get {
                    return this.columnNAMAPERUSAHAAN;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn ALAMATPERUSAHAANColumn {
                get {
                    return this.columnALAMATPERUSAHAAN;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn TELPPERUSAHAANColumn {
                get {
                    return this.columnTELPPERUSAHAAN;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn FAXPERUSAHAANColumn {
                get {
                    return this.columnFAXPERUSAHAAN;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn NOColumn {
                get {
                    return this.columnNO;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.ComponentModel.Browsable(false)]
            public int Count {
                get {
                    return this.Rows.Count;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public V_BIAYASTTRow this[int index] {
                get {
                    return ((V_BIAYASTTRow)(this.Rows[index]));
                }
            }
            
            public event V_BIAYASTTRowChangeEventHandler V_BIAYASTTRowChanging;
            
            public event V_BIAYASTTRowChangeEventHandler V_BIAYASTTRowChanged;
            
            public event V_BIAYASTTRowChangeEventHandler V_BIAYASTTRowDeleting;
            
            public event V_BIAYASTTRowChangeEventHandler V_BIAYASTTRowDeleted;
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void AddV_BIAYASTTRow(V_BIAYASTTRow row) {
                this.Rows.Add(row);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public V_BIAYASTTRow AddV_BIAYASTTRow(
                        string STARTDATE, 
                        string ENDDATE, 
                        string DATE, 
                        string CUSTOMER, 
                        string STT, 
                        string DEST, 
                        string ARMADA, 
                        string SERVICE, 
                        string BERAT, 
                        string TOTAL, 
                        string FEEMKRT, 
                        string RC, 
                        string COSTSMU, 
                        string COSTGRDH, 
                        string COSTWH, 
                        string COSTDARAT, 
                        string COSTLAUT, 
                        string COSTDELIVERY, 
                        string COSTRA, 
                        string TOTALCOST, 
                        string PROFIT, 
                        string PROFITPERCENT, 
                        string OPT1, 
                        string OPT2, 
                        string OPT3, 
                        string NAMAPERUSAHAAN, 
                        string ALAMATPERUSAHAAN, 
                        string TELPPERUSAHAAN, 
                        string FAXPERUSAHAAN, 
                        string NO) {
                V_BIAYASTTRow rowV_BIAYASTTRow = ((V_BIAYASTTRow)(this.NewRow()));
                object[] columnValuesArray = new object[] {
                        STARTDATE,
                        ENDDATE,
                        DATE,
                        CUSTOMER,
                        STT,
                        DEST,
                        ARMADA,
                        SERVICE,
                        BERAT,
                        TOTAL,
                        FEEMKRT,
                        RC,
                        COSTSMU,
                        COSTGRDH,
                        COSTWH,
                        COSTDARAT,
                        COSTLAUT,
                        COSTDELIVERY,
                        COSTRA,
                        TOTALCOST,
                        PROFIT,
                        PROFITPERCENT,
                        OPT1,
                        OPT2,
                        OPT3,
                        NAMAPERUSAHAAN,
                        ALAMATPERUSAHAAN,
                        TELPPERUSAHAAN,
                        FAXPERUSAHAAN,
                        NO};
                rowV_BIAYASTTRow.ItemArray = columnValuesArray;
                this.Rows.Add(rowV_BIAYASTTRow);
                return rowV_BIAYASTTRow;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public override global::System.Data.DataTable Clone() {
                V_BIAYASTTDataTable cln = ((V_BIAYASTTDataTable)(base.Clone()));
                cln.InitVars();
                return cln;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            protected override global::System.Data.DataTable CreateInstance() {
                return new V_BIAYASTTDataTable();
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            internal void InitVars() {
                this.columnSTARTDATE = base.Columns["STARTDATE"];
                this.columnENDDATE = base.Columns["ENDDATE"];
                this.columnDATE = base.Columns["DATE"];
                this.columnCUSTOMER = base.Columns["CUSTOMER"];
                this.columnSTT = base.Columns["STT"];
                this.columnDEST = base.Columns["DEST"];
                this.columnARMADA = base.Columns["ARMADA"];
                this.columnSERVICE = base.Columns["SERVICE"];
                this.columnBERAT = base.Columns["BERAT"];
                this.columnTOTAL = base.Columns["TOTAL"];
                this.columnFEEMKRT = base.Columns["FEEMKRT"];
                this.columnRC = base.Columns["RC"];
                this.columnCOSTSMU = base.Columns["COSTSMU"];
                this.columnCOSTGRDH = base.Columns["COSTGRDH"];
                this.columnCOSTWH = base.Columns["COSTWH"];
                this.columnCOSTDARAT = base.Columns["COSTDARAT"];
                this.columnCOSTLAUT = base.Columns["COSTLAUT"];
                this.columnCOSTDELIVERY = base.Columns["COSTDELIVERY"];
                this.columnCOSTRA = base.Columns["COSTRA"];
                this.columnTOTALCOST = base.Columns["TOTALCOST"];
                this.columnPROFIT = base.Columns["PROFIT"];
                this.columnPROFITPERCENT = base.Columns["PROFITPERCENT"];
                this.columnOPT1 = base.Columns["OPT1"];
                this.columnOPT2 = base.Columns["OPT2"];
                this.columnOPT3 = base.Columns["OPT3"];
                this.columnNAMAPERUSAHAAN = base.Columns["NAMAPERUSAHAAN"];
                this.columnALAMATPERUSAHAAN = base.Columns["ALAMATPERUSAHAAN"];
                this.columnTELPPERUSAHAAN = base.Columns["TELPPERUSAHAAN"];
                this.columnFAXPERUSAHAAN = base.Columns["FAXPERUSAHAAN"];
                this.columnNO = base.Columns["NO"];
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            private void InitClass() {
                this.columnSTARTDATE = new global::System.Data.DataColumn("STARTDATE", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnSTARTDATE);
                this.columnENDDATE = new global::System.Data.DataColumn("ENDDATE", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnENDDATE);
                this.columnDATE = new global::System.Data.DataColumn("DATE", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnDATE);
                this.columnCUSTOMER = new global::System.Data.DataColumn("CUSTOMER", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnCUSTOMER);
                this.columnSTT = new global::System.Data.DataColumn("STT", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnSTT);
                this.columnDEST = new global::System.Data.DataColumn("DEST", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnDEST);
                this.columnARMADA = new global::System.Data.DataColumn("ARMADA", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnARMADA);
                this.columnSERVICE = new global::System.Data.DataColumn("SERVICE", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnSERVICE);
                this.columnBERAT = new global::System.Data.DataColumn("BERAT", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnBERAT);
                this.columnTOTAL = new global::System.Data.DataColumn("TOTAL", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnTOTAL);
                this.columnFEEMKRT = new global::System.Data.DataColumn("FEEMKRT", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnFEEMKRT);
                this.columnRC = new global::System.Data.DataColumn("RC", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnRC);
                this.columnCOSTSMU = new global::System.Data.DataColumn("COSTSMU", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnCOSTSMU);
                this.columnCOSTGRDH = new global::System.Data.DataColumn("COSTGRDH", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnCOSTGRDH);
                this.columnCOSTWH = new global::System.Data.DataColumn("COSTWH", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnCOSTWH);
                this.columnCOSTDARAT = new global::System.Data.DataColumn("COSTDARAT", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnCOSTDARAT);
                this.columnCOSTLAUT = new global::System.Data.DataColumn("COSTLAUT", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnCOSTLAUT);
                this.columnCOSTDELIVERY = new global::System.Data.DataColumn("COSTDELIVERY", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnCOSTDELIVERY);
                this.columnCOSTRA = new global::System.Data.DataColumn("COSTRA", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnCOSTRA);
                this.columnTOTALCOST = new global::System.Data.DataColumn("TOTALCOST", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnTOTALCOST);
                this.columnPROFIT = new global::System.Data.DataColumn("PROFIT", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnPROFIT);
                this.columnPROFITPERCENT = new global::System.Data.DataColumn("PROFITPERCENT", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnPROFITPERCENT);
                this.columnOPT1 = new global::System.Data.DataColumn("OPT1", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnOPT1);
                this.columnOPT2 = new global::System.Data.DataColumn("OPT2", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnOPT2);
                this.columnOPT3 = new global::System.Data.DataColumn("OPT3", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnOPT3);
                this.columnNAMAPERUSAHAAN = new global::System.Data.DataColumn("NAMAPERUSAHAAN", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnNAMAPERUSAHAAN);
                this.columnALAMATPERUSAHAAN = new global::System.Data.DataColumn("ALAMATPERUSAHAAN", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnALAMATPERUSAHAAN);
                this.columnTELPPERUSAHAAN = new global::System.Data.DataColumn("TELPPERUSAHAAN", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnTELPPERUSAHAAN);
                this.columnFAXPERUSAHAAN = new global::System.Data.DataColumn("FAXPERUSAHAAN", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnFAXPERUSAHAAN);
                this.columnNO = new global::System.Data.DataColumn("NO", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnNO);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public V_BIAYASTTRow NewV_BIAYASTTRow() {
                return ((V_BIAYASTTRow)(this.NewRow()));
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            protected override global::System.Data.DataRow NewRowFromBuilder(global::System.Data.DataRowBuilder builder) {
                return new V_BIAYASTTRow(builder);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            protected override global::System.Type GetRowType() {
                return typeof(V_BIAYASTTRow);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            protected override void OnRowChanged(global::System.Data.DataRowChangeEventArgs e) {
                base.OnRowChanged(e);
                if ((this.V_BIAYASTTRowChanged != null)) {
                    this.V_BIAYASTTRowChanged(this, new V_BIAYASTTRowChangeEvent(((V_BIAYASTTRow)(e.Row)), e.Action));
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            protected override void OnRowChanging(global::System.Data.DataRowChangeEventArgs e) {
                base.OnRowChanging(e);
                if ((this.V_BIAYASTTRowChanging != null)) {
                    this.V_BIAYASTTRowChanging(this, new V_BIAYASTTRowChangeEvent(((V_BIAYASTTRow)(e.Row)), e.Action));
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            protected override void OnRowDeleted(global::System.Data.DataRowChangeEventArgs e) {
                base.OnRowDeleted(e);
                if ((this.V_BIAYASTTRowDeleted != null)) {
                    this.V_BIAYASTTRowDeleted(this, new V_BIAYASTTRowChangeEvent(((V_BIAYASTTRow)(e.Row)), e.Action));
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            protected override void OnRowDeleting(global::System.Data.DataRowChangeEventArgs e) {
                base.OnRowDeleting(e);
                if ((this.V_BIAYASTTRowDeleting != null)) {
                    this.V_BIAYASTTRowDeleting(this, new V_BIAYASTTRowChangeEvent(((V_BIAYASTTRow)(e.Row)), e.Action));
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void RemoveV_BIAYASTTRow(V_BIAYASTTRow row) {
                this.Rows.Remove(row);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public static global::System.Xml.Schema.XmlSchemaComplexType GetTypedTableSchema(global::System.Xml.Schema.XmlSchemaSet xs) {
                global::System.Xml.Schema.XmlSchemaComplexType type = new global::System.Xml.Schema.XmlSchemaComplexType();
                global::System.Xml.Schema.XmlSchemaSequence sequence = new global::System.Xml.Schema.XmlSchemaSequence();
                dsBIAYA ds = new dsBIAYA();
                global::System.Xml.Schema.XmlSchemaAny any1 = new global::System.Xml.Schema.XmlSchemaAny();
                any1.Namespace = "http://www.w3.org/2001/XMLSchema";
                any1.MinOccurs = new decimal(0);
                any1.MaxOccurs = decimal.MaxValue;
                any1.ProcessContents = global::System.Xml.Schema.XmlSchemaContentProcessing.Lax;
                sequence.Items.Add(any1);
                global::System.Xml.Schema.XmlSchemaAny any2 = new global::System.Xml.Schema.XmlSchemaAny();
                any2.Namespace = "urn:schemas-microsoft-com:xml-diffgram-v1";
                any2.MinOccurs = new decimal(1);
                any2.ProcessContents = global::System.Xml.Schema.XmlSchemaContentProcessing.Lax;
                sequence.Items.Add(any2);
                global::System.Xml.Schema.XmlSchemaAttribute attribute1 = new global::System.Xml.Schema.XmlSchemaAttribute();
                attribute1.Name = "namespace";
                attribute1.FixedValue = ds.Namespace;
                type.Attributes.Add(attribute1);
                global::System.Xml.Schema.XmlSchemaAttribute attribute2 = new global::System.Xml.Schema.XmlSchemaAttribute();
                attribute2.Name = "tableTypeName";
                attribute2.FixedValue = "V_BIAYASTTDataTable";
                type.Attributes.Add(attribute2);
                type.Particle = sequence;
                global::System.Xml.Schema.XmlSchema dsSchema = ds.GetSchemaSerializable();
                if (xs.Contains(dsSchema.TargetNamespace)) {
                    global::System.IO.MemoryStream s1 = new global::System.IO.MemoryStream();
                    global::System.IO.MemoryStream s2 = new global::System.IO.MemoryStream();
                    try {
                        global::System.Xml.Schema.XmlSchema schema = null;
                        dsSchema.Write(s1);
                        for (global::System.Collections.IEnumerator schemas = xs.Schemas(dsSchema.TargetNamespace).GetEnumerator(); schemas.MoveNext(); ) {
                            schema = ((global::System.Xml.Schema.XmlSchema)(schemas.Current));
                            s2.SetLength(0);
                            schema.Write(s2);
                            if ((s1.Length == s2.Length)) {
                                s1.Position = 0;
                                s2.Position = 0;
                                for (; ((s1.Position != s1.Length) 
                                            && (s1.ReadByte() == s2.ReadByte())); ) {
                                    ;
                                }
                                if ((s1.Position == s1.Length)) {
                                    return type;
                                }
                            }
                        }
                    }
                    finally {
                        if ((s1 != null)) {
                            s1.Close();
                        }
                        if ((s2 != null)) {
                            s2.Close();
                        }
                    }
                }
                xs.Add(dsSchema);
                return type;
            }
        }
        
        /// <summary>
        ///Represents strongly named DataRow class.
        ///</summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "2.0.0.0")]
        public partial class V_BIAYASTTRow : global::System.Data.DataRow {
            
            private V_BIAYASTTDataTable tableV_BIAYASTT;
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            internal V_BIAYASTTRow(global::System.Data.DataRowBuilder rb) : 
                    base(rb) {
                this.tableV_BIAYASTT = ((V_BIAYASTTDataTable)(this.Table));
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public string STARTDATE {
                get {
                    try {
                        return ((string)(this[this.tableV_BIAYASTT.STARTDATEColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'STARTDATE\' in table \'V_BIAYASTT\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tableV_BIAYASTT.STARTDATEColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public string ENDDATE {
                get {
                    try {
                        return ((string)(this[this.tableV_BIAYASTT.ENDDATEColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'ENDDATE\' in table \'V_BIAYASTT\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tableV_BIAYASTT.ENDDATEColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public string DATE {
                get {
                    try {
                        return ((string)(this[this.tableV_BIAYASTT.DATEColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'DATE\' in table \'V_BIAYASTT\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tableV_BIAYASTT.DATEColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public string CUSTOMER {
                get {
                    try {
                        return ((string)(this[this.tableV_BIAYASTT.CUSTOMERColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'CUSTOMER\' in table \'V_BIAYASTT\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tableV_BIAYASTT.CUSTOMERColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public string STT {
                get {
                    try {
                        return ((string)(this[this.tableV_BIAYASTT.STTColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'STT\' in table \'V_BIAYASTT\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tableV_BIAYASTT.STTColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public string DEST {
                get {
                    try {
                        return ((string)(this[this.tableV_BIAYASTT.DESTColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'DEST\' in table \'V_BIAYASTT\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tableV_BIAYASTT.DESTColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public string ARMADA {
                get {
                    try {
                        return ((string)(this[this.tableV_BIAYASTT.ARMADAColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'ARMADA\' in table \'V_BIAYASTT\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tableV_BIAYASTT.ARMADAColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public string SERVICE {
                get {
                    try {
                        return ((string)(this[this.tableV_BIAYASTT.SERVICEColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'SERVICE\' in table \'V_BIAYASTT\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tableV_BIAYASTT.SERVICEColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public string BERAT {
                get {
                    try {
                        return ((string)(this[this.tableV_BIAYASTT.BERATColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'BERAT\' in table \'V_BIAYASTT\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tableV_BIAYASTT.BERATColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public string TOTAL {
                get {
                    try {
                        return ((string)(this[this.tableV_BIAYASTT.TOTALColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'TOTAL\' in table \'V_BIAYASTT\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tableV_BIAYASTT.TOTALColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public string FEEMKRT {
                get {
                    try {
                        return ((string)(this[this.tableV_BIAYASTT.FEEMKRTColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'FEEMKRT\' in table \'V_BIAYASTT\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tableV_BIAYASTT.FEEMKRTColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public string RC {
                get {
                    try {
                        return ((string)(this[this.tableV_BIAYASTT.RCColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'RC\' in table \'V_BIAYASTT\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tableV_BIAYASTT.RCColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public string COSTSMU {
                get {
                    try {
                        return ((string)(this[this.tableV_BIAYASTT.COSTSMUColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'COSTSMU\' in table \'V_BIAYASTT\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tableV_BIAYASTT.COSTSMUColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public string COSTGRDH {
                get {
                    try {
                        return ((string)(this[this.tableV_BIAYASTT.COSTGRDHColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'COSTGRDH\' in table \'V_BIAYASTT\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tableV_BIAYASTT.COSTGRDHColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public string COSTWH {
                get {
                    try {
                        return ((string)(this[this.tableV_BIAYASTT.COSTWHColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'COSTWH\' in table \'V_BIAYASTT\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tableV_BIAYASTT.COSTWHColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public string COSTDARAT {
                get {
                    try {
                        return ((string)(this[this.tableV_BIAYASTT.COSTDARATColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'COSTDARAT\' in table \'V_BIAYASTT\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tableV_BIAYASTT.COSTDARATColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public string COSTLAUT {
                get {
                    try {
                        return ((string)(this[this.tableV_BIAYASTT.COSTLAUTColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'COSTLAUT\' in table \'V_BIAYASTT\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tableV_BIAYASTT.COSTLAUTColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public string COSTDELIVERY {
                get {
                    try {
                        return ((string)(this[this.tableV_BIAYASTT.COSTDELIVERYColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'COSTDELIVERY\' in table \'V_BIAYASTT\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tableV_BIAYASTT.COSTDELIVERYColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public string COSTRA {
                get {
                    try {
                        return ((string)(this[this.tableV_BIAYASTT.COSTRAColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'COSTRA\' in table \'V_BIAYASTT\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tableV_BIAYASTT.COSTRAColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public string TOTALCOST {
                get {
                    try {
                        return ((string)(this[this.tableV_BIAYASTT.TOTALCOSTColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'TOTALCOST\' in table \'V_BIAYASTT\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tableV_BIAYASTT.TOTALCOSTColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public string PROFIT {
                get {
                    try {
                        return ((string)(this[this.tableV_BIAYASTT.PROFITColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'PROFIT\' in table \'V_BIAYASTT\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tableV_BIAYASTT.PROFITColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public string PROFITPERCENT {
                get {
                    try {
                        return ((string)(this[this.tableV_BIAYASTT.PROFITPERCENTColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'PROFITPERCENT\' in table \'V_BIAYASTT\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tableV_BIAYASTT.PROFITPERCENTColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public string OPT1 {
                get {
                    try {
                        return ((string)(this[this.tableV_BIAYASTT.OPT1Column]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'OPT1\' in table \'V_BIAYASTT\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tableV_BIAYASTT.OPT1Column] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public string OPT2 {
                get {
                    try {
                        return ((string)(this[this.tableV_BIAYASTT.OPT2Column]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'OPT2\' in table \'V_BIAYASTT\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tableV_BIAYASTT.OPT2Column] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public string OPT3 {
                get {
                    try {
                        return ((string)(this[this.tableV_BIAYASTT.OPT3Column]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'OPT3\' in table \'V_BIAYASTT\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tableV_BIAYASTT.OPT3Column] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public string NAMAPERUSAHAAN {
                get {
                    try {
                        return ((string)(this[this.tableV_BIAYASTT.NAMAPERUSAHAANColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'NAMAPERUSAHAAN\' in table \'V_BIAYASTT\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tableV_BIAYASTT.NAMAPERUSAHAANColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public string ALAMATPERUSAHAAN {
                get {
                    try {
                        return ((string)(this[this.tableV_BIAYASTT.ALAMATPERUSAHAANColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'ALAMATPERUSAHAAN\' in table \'V_BIAYASTT\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tableV_BIAYASTT.ALAMATPERUSAHAANColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public string TELPPERUSAHAAN {
                get {
                    try {
                        return ((string)(this[this.tableV_BIAYASTT.TELPPERUSAHAANColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'TELPPERUSAHAAN\' in table \'V_BIAYASTT\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tableV_BIAYASTT.TELPPERUSAHAANColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public string FAXPERUSAHAAN {
                get {
                    try {
                        return ((string)(this[this.tableV_BIAYASTT.FAXPERUSAHAANColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'FAXPERUSAHAAN\' in table \'V_BIAYASTT\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tableV_BIAYASTT.FAXPERUSAHAANColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public string NO {
                get {
                    try {
                        return ((string)(this[this.tableV_BIAYASTT.NOColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'NO\' in table \'V_BIAYASTT\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tableV_BIAYASTT.NOColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IsSTARTDATENull() {
                return this.IsNull(this.tableV_BIAYASTT.STARTDATEColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetSTARTDATENull() {
                this[this.tableV_BIAYASTT.STARTDATEColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IsENDDATENull() {
                return this.IsNull(this.tableV_BIAYASTT.ENDDATEColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetENDDATENull() {
                this[this.tableV_BIAYASTT.ENDDATEColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IsDATENull() {
                return this.IsNull(this.tableV_BIAYASTT.DATEColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetDATENull() {
                this[this.tableV_BIAYASTT.DATEColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IsCUSTOMERNull() {
                return this.IsNull(this.tableV_BIAYASTT.CUSTOMERColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetCUSTOMERNull() {
                this[this.tableV_BIAYASTT.CUSTOMERColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IsSTTNull() {
                return this.IsNull(this.tableV_BIAYASTT.STTColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetSTTNull() {
                this[this.tableV_BIAYASTT.STTColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IsDESTNull() {
                return this.IsNull(this.tableV_BIAYASTT.DESTColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetDESTNull() {
                this[this.tableV_BIAYASTT.DESTColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IsARMADANull() {
                return this.IsNull(this.tableV_BIAYASTT.ARMADAColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetARMADANull() {
                this[this.tableV_BIAYASTT.ARMADAColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IsSERVICENull() {
                return this.IsNull(this.tableV_BIAYASTT.SERVICEColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetSERVICENull() {
                this[this.tableV_BIAYASTT.SERVICEColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IsBERATNull() {
                return this.IsNull(this.tableV_BIAYASTT.BERATColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetBERATNull() {
                this[this.tableV_BIAYASTT.BERATColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IsTOTALNull() {
                return this.IsNull(this.tableV_BIAYASTT.TOTALColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetTOTALNull() {
                this[this.tableV_BIAYASTT.TOTALColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IsFEEMKRTNull() {
                return this.IsNull(this.tableV_BIAYASTT.FEEMKRTColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetFEEMKRTNull() {
                this[this.tableV_BIAYASTT.FEEMKRTColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IsRCNull() {
                return this.IsNull(this.tableV_BIAYASTT.RCColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetRCNull() {
                this[this.tableV_BIAYASTT.RCColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IsCOSTSMUNull() {
                return this.IsNull(this.tableV_BIAYASTT.COSTSMUColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetCOSTSMUNull() {
                this[this.tableV_BIAYASTT.COSTSMUColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IsCOSTGRDHNull() {
                return this.IsNull(this.tableV_BIAYASTT.COSTGRDHColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetCOSTGRDHNull() {
                this[this.tableV_BIAYASTT.COSTGRDHColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IsCOSTWHNull() {
                return this.IsNull(this.tableV_BIAYASTT.COSTWHColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetCOSTWHNull() {
                this[this.tableV_BIAYASTT.COSTWHColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IsCOSTDARATNull() {
                return this.IsNull(this.tableV_BIAYASTT.COSTDARATColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetCOSTDARATNull() {
                this[this.tableV_BIAYASTT.COSTDARATColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IsCOSTLAUTNull() {
                return this.IsNull(this.tableV_BIAYASTT.COSTLAUTColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetCOSTLAUTNull() {
                this[this.tableV_BIAYASTT.COSTLAUTColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IsCOSTDELIVERYNull() {
                return this.IsNull(this.tableV_BIAYASTT.COSTDELIVERYColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetCOSTDELIVERYNull() {
                this[this.tableV_BIAYASTT.COSTDELIVERYColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IsCOSTRANull() {
                return this.IsNull(this.tableV_BIAYASTT.COSTRAColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetCOSTRANull() {
                this[this.tableV_BIAYASTT.COSTRAColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IsTOTALCOSTNull() {
                return this.IsNull(this.tableV_BIAYASTT.TOTALCOSTColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetTOTALCOSTNull() {
                this[this.tableV_BIAYASTT.TOTALCOSTColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IsPROFITNull() {
                return this.IsNull(this.tableV_BIAYASTT.PROFITColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetPROFITNull() {
                this[this.tableV_BIAYASTT.PROFITColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IsPROFITPERCENTNull() {
                return this.IsNull(this.tableV_BIAYASTT.PROFITPERCENTColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetPROFITPERCENTNull() {
                this[this.tableV_BIAYASTT.PROFITPERCENTColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IsOPT1Null() {
                return this.IsNull(this.tableV_BIAYASTT.OPT1Column);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetOPT1Null() {
                this[this.tableV_BIAYASTT.OPT1Column] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IsOPT2Null() {
                return this.IsNull(this.tableV_BIAYASTT.OPT2Column);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetOPT2Null() {
                this[this.tableV_BIAYASTT.OPT2Column] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IsOPT3Null() {
                return this.IsNull(this.tableV_BIAYASTT.OPT3Column);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetOPT3Null() {
                this[this.tableV_BIAYASTT.OPT3Column] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IsNAMAPERUSAHAANNull() {
                return this.IsNull(this.tableV_BIAYASTT.NAMAPERUSAHAANColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetNAMAPERUSAHAANNull() {
                this[this.tableV_BIAYASTT.NAMAPERUSAHAANColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IsALAMATPERUSAHAANNull() {
                return this.IsNull(this.tableV_BIAYASTT.ALAMATPERUSAHAANColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetALAMATPERUSAHAANNull() {
                this[this.tableV_BIAYASTT.ALAMATPERUSAHAANColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IsTELPPERUSAHAANNull() {
                return this.IsNull(this.tableV_BIAYASTT.TELPPERUSAHAANColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetTELPPERUSAHAANNull() {
                this[this.tableV_BIAYASTT.TELPPERUSAHAANColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IsFAXPERUSAHAANNull() {
                return this.IsNull(this.tableV_BIAYASTT.FAXPERUSAHAANColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetFAXPERUSAHAANNull() {
                this[this.tableV_BIAYASTT.FAXPERUSAHAANColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IsNONull() {
                return this.IsNull(this.tableV_BIAYASTT.NOColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetNONull() {
                this[this.tableV_BIAYASTT.NOColumn] = global::System.Convert.DBNull;
            }
        }
        
        /// <summary>
        ///Row event argument class
        ///</summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "2.0.0.0")]
        public class V_BIAYASTTRowChangeEvent : global::System.EventArgs {
            
            private V_BIAYASTTRow eventRow;
            
            private global::System.Data.DataRowAction eventAction;
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public V_BIAYASTTRowChangeEvent(V_BIAYASTTRow row, global::System.Data.DataRowAction action) {
                this.eventRow = row;
                this.eventAction = action;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public V_BIAYASTTRow Row {
                get {
                    return this.eventRow;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataRowAction Action {
                get {
                    return this.eventAction;
                }
            }
        }
    }
}

#pragma warning restore 1591